In [1]:
import polars as pl
import os
import glob
from tqdm import tqdm

## Functions

In [2]:
def reorder_cols(df: pl.DataFrame) -> pl.DataFrame:
	"""
	Reorders the columns of a DataFrame so that 'sample' is the first column if it exists.
	"""
	cols = df.columns

	if "sample" in cols:
		cols.remove("sample")
		cols.insert(0, "sample")

	return df[cols]

In [3]:
def summarize_res(df: pl.DataFrame) -> pl.DataFrame:
	
	bool_cols = df['filter_1_mutation_intra_hairpin_loop':'filter_8_low_quality'].columns
	str_cols = df['msec_filter_123':'msec_filter_all'].columns
	n_variants = df.height

	# Initialize a dictionary
	results = {
		"filter": [],
		"percentage": [],
		"n_failed": []
	}

	# Populate the dictionary inside the loops
	for col in bool_cols:
		n_failed = df[col].sum() # Sum counts True values
		
		results["filter"].append(col)
		results["percentage"].append((n_failed / n_variants) * 100)
		results["n_failed"].append(n_failed)

	for col in str_cols:
		n_failed = df.filter(~pl.col(col).is_null()).height # Count non-nulls
		
		results["filter"].append(col)
		results["percentage"].append((n_failed / n_variants) * 100)
		results["n_failed"].append(n_failed)

	# Create DataFrame from the dictionary
	return pl.DataFrame(results).with_columns(pl.lit(n_variants).alias("total_variants"))

### MicroSEC filter Description

The MicroSEC pipeline contains 8 filtering processes.  

- Filter 1  : Shorter-supporting lengths distribute too short to occur (1-1 and 1-2).  
	- Filter 1-1: P-values are less than the threshold_p(default: 10^(-6)).  
	- Filter 1-2: The shorter-supporting lengths distributed over less than 75% of the read length.  
- Filter 2  : Hairpin-structure induced error detection (2-1 and 2-2).  
	- Filter 2-1: Palindromic sequences exist within 200 bases.  
	- Filter 2-2: >=50% mutation-supporting reads contains a reverse complementary sequence of the opposite strand consisting >= 15 bases.  
- Filter 3  : 3'-/5'-supporting lengths are too densely distributed to occur (3-1 and 3-2).  
	- Filter 3-1: P-values are less than the threshold_p(default: 10^(-6)).  
	- Filter 3-2: The distributions of 3'-/5'-supporting lengths are within 75% of the read length.  
- Filter 4  : >=15% mutations were called by chimeric reads comprising two distant regions.  
- Filter 5  : >=50% mutations were called by soft-clipped reads.  
- Filter 6  : Mutations locating at simple repeat sequences.  
- Filter 7  : Indel mutations locating at a >=15 homopolymer.  
- Filter 8  : >=10% of bases are low quality (Quality score <18) in the mutation supporting reads.  

Filter 1, 2, 3, and 4 detect possible FFPE artifacts.  
Filter 5 may also be FFPE artifacts or mapping errors.  
Filter 6, 7, and 8 detect frequent errors caused by the next generation sequencing platform.  
Supporting lengths are adjusted considering small repeat sequences around the mutations.  
  
Results are saved in a tsv file.  

github url: https://github.com/MANO-B/MicroSEC

## Main
### VCF

In [23]:
msec_paths = sorted(glob.glob("../vcf-micr-svf/*/*.microsec.tsv"))

all_res = []

for path in tqdm(msec_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t", infer_schema_length = 1000).rename(lambda x : x.lower())
	
	all_res.append(df)
	
final_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

100%|██████████| 1641/1641 [03:08<00:00,  8.73it/s]

In [24]:
final_df

shape: (46_352, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-100115 ┆ 12-del   ┆ chr1  ┆ 11190697  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr1  ┆ 16262742  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr1  ┆ 45797760  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr10 ┆ 43601830  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-100115 ┆ 1-snv    ┆ chr11 ┆ 118307334 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-213329 ┆ 1-snv    ┆ chr17 ┆ 37856504  ┆ … ┆ null       ┆ null       ┆ null       ┆ filter 1: │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213329 ┆ 1-snv    ┆ chr22 ┆ 29108003  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr4  ┆ 1920021   ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr7  ┆ 55268044  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chrX  ┆ 66765516  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆           │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [25]:
## Samples that could be processed
final_df["sample"].unique()

shape: (1_641,)
Series: 'sample' [str]
[
	"ORD-1691406-01"
	"ORD-1050682-01"
	"ORD-1959107-01"
	"ORD-1789900-01"
	"ORD-1748047-01"
	…
	"ORD-1526119-01"
	"ORD-1800292-01"
	"ORD-1742473-01"
	"ORD-1622425-01"
	"ORD-1556064-01"
]

In [26]:
# All Filters
arti_all_filter = final_df.filter(~pl.col("msec_filter_all").is_null())
display(arti_all_filter)
# Number of Samples with >= 1 artifacts
arti_all_filter["sample"].n_unique()

shape: (4_836, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-100115 ┆ 12-del   ┆ chr1  ┆ 11190697  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 9-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-100115 ┆ 12-del   ┆ chr3  ┆ 41266087  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 9-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-102034 ┆ 12-del   ┆ chr1  ┆ 11190697  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ filter 1: │
│ 2-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-104200 ┆ 1-del    ┆ chr11 ┆ 118359946 ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-104200 ┆ 1-ins    ┆ chr12 ┆ 18691260  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-213160 ┆ 1-snv    ┆ chr17 ┆ 29483000  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-213160 ┆ 16-del   ┆ chr2  ┆ 225422558 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 2-ins    ┆ chr8  ┆ 117864264 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 3-ins    ┆ chr16 ┆ 3778439   ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ filter 3: │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

1184

In [27]:
# Filter 1234
arti_filter_1234 = final_df.filter(~pl.col("msec_filter_1234").is_null())
display(arti_filter_1234)
# Number of Samples with >= 1 artifacts
arti_filter_1234["sample"].n_unique()

shape: (1_447, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-100115 ┆ 12-del   ┆ chr3  ┆ 41266087  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 9-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-104200 ┆ 1-ins    ┆ chr12 ┆ 18691260  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-104200 ┆ 1-ins    ┆ chr17 ┆ 41204899  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but rea…  │
│ ORD-104848 ┆ 1-snv    ┆ chr4  ┆ 55140704  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-104925 ┆ 1-ins    ┆ chr2  ┆ 61726060  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-211780 ┆ 1-snv    ┆ chr3  ┆ 178952085 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 8-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-211884 ┆ 1-snv    ┆ chr2  ┆ 25463568  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 2-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 16-del   ┆ chr2  ┆ 225422558 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 2-ins    ┆ chr8  ┆ 117864264 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

652

In [31]:
summarize_res(final_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 0.914739   ┆ 424      ┆ 46352          │
│ filter_2_hairpin_structure      ┆ 0.030204   ┆ 14       ┆ 46352          │
│ filter_3_microhomology_induced… ┆ 1.382896   ┆ 641      ┆ 46352          │
│ filter_4_highly_homologous_reg… ┆ 1.279341   ┆ 593      ┆ 46352          │
│ filter_5_soft_clipped_reads     ┆ 0.509147   ┆ 236      ┆ 46352          │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 2.524163   ┆ 1170     ┆ 46352          │
│ filter_8_low_quality            ┆ 3.21669    ┆ 1491     ┆ 46352          │
│ msec_filter_123                 ┆ 1.876942   ┆ 870      ┆ 46352          │
│ msec_filter_1234                ┆ 3.121764   ┆ 1447     ┆ 46352          │
│ msec_filter_all                 ┆ 10.433207  ┆ 4836     ┆ 46352          │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [32]:
summarize_res(arti_filter_1234)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 29.302004  ┆ 424      ┆ 1447           │
│ filter_2_hairpin_structure      ┆ 0.967519   ┆ 14       ┆ 1447           │
│ filter_3_microhomology_induced… ┆ 44.298549  ┆ 641      ┆ 1447           │
│ filter_4_highly_homologous_reg… ┆ 40.981341  ┆ 593      ┆ 1447           │
│ filter_5_soft_clipped_reads     ┆ 4.215619   ┆ 61       ┆ 1447           │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 11.817554  ┆ 171      ┆ 1447           │
│ filter_8_low_quality            ┆ 14.098134  ┆ 204      ┆ 1447           │
│ msec_filter_123                 ┆ 60.124395  ┆ 870      ┆ 1447           │
│ msec_filter_1234                ┆ 100.0      ┆ 1447     ┆ 1447           │
│ msec_filter_all                 ┆ 100.0      ┆ 1447     ┆ 1447           │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [30]:
summarize_res(arti_all_filter)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 8.767577   ┆ 424      ┆ 4836           │
│ filter_2_hairpin_structure      ┆ 0.289495   ┆ 14       ┆ 4836           │
│ filter_3_microhomology_induced… ┆ 13.254756  ┆ 641      ┆ 4836           │
│ filter_4_highly_homologous_reg… ┆ 12.2622    ┆ 593      ┆ 4836           │
│ filter_5_soft_clipped_reads     ┆ 4.880066   ┆ 236      ┆ 4836           │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 24.193548  ┆ 1170     ┆ 4836           │
│ filter_8_low_quality            ┆ 30.831266  ┆ 1491     ┆ 4836           │
│ msec_filter_123                 ┆ 17.990074  ┆ 870      ┆ 4836           │
│ msec_filter_1234                ┆ 29.921423  ┆ 1447     ┆ 4836           │
│ msec_filter_all                 ┆ 100.0      ┆ 4836     ┆ 4836           │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

### XML

In [34]:
msec_paths = sorted(glob.glob("../xml-micr-svf/*/*.microsec.tsv"))
len(msec_paths)

1606

In [35]:
all_res = []

for path in tqdm(msec_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t").rename(lambda x: x.lower())
	
	all_res.append(df)
	
final_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

100%|██████████| 1606/1606 [00:50<00:00, 31.66it/s]

In [36]:
final_df

shape: (21_599, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-100115 ┆ chr1  ┆ 11190697  ┆ CGTGGTGGCG ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 9-01       ┆       ┆           ┆ GCA        ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-100115 ┆ chr1  ┆ 16262742  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr1  ┆ 45797760  ┆ T          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr10 ┆ 43601830  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-100115 ┆ chr11 ┆ 118307334 ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 9-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-213329 ┆ chr17 ┆ 37856504  ┆ G          ┆ … ┆ null       ┆ null      ┆ null      ┆ filter 1: │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213329 ┆ chr22 ┆ 29108003  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chr4  ┆ 1920021   ┆ A          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chr7  ┆ 55268044  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
│ ORD-213329 ┆ chrX  ┆ 66765516  ┆ C          ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
## Samples that could be processed
final_df["sample"].unique()

shape: (1_606,)
Series: 'sample' [str]
[
	"ORD-1993016-01"
	"ORD-2104088-01"
	"ORD-2069193-01"
	"ORD-1815132-01"
	"ORD-1562107-01"
	…
	"ORD-1296818-01"
	"ORD-1867608-01"
	"ORD-1764534-01"
	"ORD-1956538-01"
	"ORD-1809251-01"
]

In [17]:
# All artifacts
arti_all_filter = final_df.filter(~pl.col("msec_filter_all").is_null())
display(arti_all_filter)
# Number of Samples with >= 1 artifacts
arti_all_filter["sample"].n_unique()

shape: (1_185, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-100115 ┆ chr1  ┆ 11190697  ┆ CGTGGTGGCG ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 9-01       ┆       ┆           ┆ GCA        ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-102034 ┆ chr1  ┆ 11190697  ┆ CGTGGTGGCG ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ filter 1: │
│ 2-01       ┆       ┆           ┆ GCA        ┆   ┆            ┆           ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-104848 ┆ chr4  ┆ 55140704  ┆ G          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-104925 ┆ chr6  ┆ 33287880  ┆ GCCT       ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 0-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-105068 ┆ chr19 ┆ 11098593  ┆ G          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 2-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-213160 ┆ chr17 ┆ 29483000  ┆ G          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-213160 ┆ chr2  ┆ 225422558 ┆ TTTCATCCAT ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 3: │
│ 6-01       ┆       ┆           ┆ GGTCATC    ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr8  ┆ 117864264 ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr11 ┆ 118343321 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr16 ┆ 3778439   ┆ T          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ filter 3: │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

764

In [18]:
# Filter 1234
arti_filter_1234 = final_df.filter(~pl.col("msec_filter_1234").is_null())
display(arti_filter_1234)
# Number of Samples with >= 1 artifacts
arti_filter_1234["sample"].n_unique()

shape: (283, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-104848 ┆ chr4  ┆ 55140704  ┆ G          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-104925 ┆ chr6  ┆ 33287880  ┆ GCCT       ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 0-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-111144 ┆ chr16 ┆ 89880936  ┆ GA         ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 5-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-111406 ┆ chr2  ┆ 212288966 ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 3-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-112730 ┆ chr7  ┆ 116412029 ┆ CTACTTTTCC ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 3: │
│ 5-01       ┆       ┆           ┆ AGAAG      ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-211780 ┆ chr3  ┆ 178952085 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 8-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-211884 ┆ chr2  ┆ 25463568  ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 1: │
│ 2-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr2  ┆ 225422558 ┆ TTTCATCCAT ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 3: │
│ 6-01       ┆       ┆           ┆ GGTCATC    ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr8  ┆ 117864264 ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr11 ┆ 118343321 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

243

In [19]:
summarize_res(final_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 0.763924   ┆ 165      ┆ 21599          │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 21599          │
│ filter_3_microhomology_induced… ┆ 0.648178   ┆ 140      ┆ 21599          │
│ filter_4_highly_homologous_reg… ┆ 0.208343   ┆ 45       ┆ 21599          │
│ filter_5_soft_clipped_reads     ┆ 0.717626   ┆ 155      ┆ 21599          │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.00926    ┆ 2        ┆ 21599          │
│ filter_8_low_quality            ┆ 1.824159   ┆ 394      ┆ 21599          │
│ msec_filter_123                 ┆ 1.101903   ┆ 238      ┆ 21599          │
│ msec_filter_1234                ┆ 1.310246   ┆ 283      ┆ 21599          │
│ msec_filter_all                 ┆ 5.486365   ┆ 1185     ┆ 21599          │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [20]:
summarize_res(arti_filter_1234)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 58.303887  ┆ 165      ┆ 283            │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 283            │
│ filter_3_microhomology_induced… ┆ 49.469965  ┆ 140      ┆ 283            │
│ filter_4_highly_homologous_reg… ┆ 15.90106   ┆ 45       ┆ 283            │
│ filter_5_soft_clipped_reads     ┆ 8.480565   ┆ 24       ┆ 283            │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.0        ┆ 0        ┆ 283            │
│ filter_8_low_quality            ┆ 2.826855   ┆ 8        ┆ 283            │
│ msec_filter_123                 ┆ 84.09894   ┆ 238      ┆ 283            │
│ msec_filter_1234                ┆ 100.0      ┆ 283      ┆ 283            │
│ msec_filter_all                 ┆ 100.0      ┆ 283      ┆ 283            │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [21]:
summarize_res(arti_all_filter)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_variants │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ str                             ┆ f64        ┆ i64      ┆ i32            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ filter_1_mutation_intra_hairpi… ┆ 13.924051  ┆ 165      ┆ 1185           │
│ filter_2_hairpin_structure      ┆ 0.0        ┆ 0        ┆ 1185           │
│ filter_3_microhomology_induced… ┆ 11.814346  ┆ 140      ┆ 1185           │
│ filter_4_highly_homologous_reg… ┆ 3.797468   ┆ 45       ┆ 1185           │
│ filter_5_soft_clipped_reads     ┆ 13.080169  ┆ 155      ┆ 1185           │
│ …                               ┆ …          ┆ …        ┆ …              │
│ filter_7_mutation_at_homopolym… ┆ 0.168776   ┆ 2        ┆ 1185           │
│ filter_8_low_quality            ┆ 33.248945  ┆ 394      ┆ 1185           │
│ msec_filter_123                 ┆ 20.084388  ┆ 238      ┆ 1185           │
│ msec_filter_1234                ┆ 23.881857  ┆ 283      ┆ 1185           │
│ msec_filter_all                 ┆ 100.0      ┆ 1185     ┆ 1185           │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘