In [79]:
import polars as pl
import os
import glob

## Functions

In [80]:
def reorder_cols(df: pl.DataFrame) -> pl.DataFrame:
    cols = df.columns

    if "sample" in cols:
        cols.remove("sample")
        cols.insert(0, "sample")

    return df[cols]

In [81]:
def summarize_res(df: pl.DataFrame) -> pl.DataFrame:
    
    bool_cols = df['filter_1_mutation_intra_hairpin_loop':'filter_8_low_quality'].columns
    str_cols = df['msec_filter_123':'msec_filter_all'].columns
    n_variants = df.height

    # 1. Initialize a dictionary with empty lists for your columns
    results = {
        "filter": [],
        "percentage": [],
        "n_failed": []
    }

    # 2. Populate the dictionary inside your loops
    for col in bool_cols:
        n_failed = df[col].sum() # Sum counts True values
        
        results["filter"].append(f"%_{col}")
        results["percentage"].append((n_failed / n_variants) * 100)
        results["n_failed"].append(n_failed)

    for col in str_cols:
        n_failed = df.filter(~pl.col(col).is_null()).height # Count non-nulls
        
        results["filter"].append(f"%_{col}")
        results["percentage"].append((n_failed / n_variants) * 100)
        results["n_failed"].append(n_failed)

    # 3. Create DataFrame directly from the dictionary
    return pl.DataFrame(results).with_columns(pl.lit(n_variants).alias("total_varints"))

## Main

In [82]:
msec_paths = sorted(glob.glob("../vcf-micr-svf/*/*.microsec.tsv"))

all_res = []

for i, path in enumerate(msec_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t").rename(lambda x : x.lower())
    
	all_res.append(df)
	print(f"{i+1} Processed {sample}")
    
final_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

1 Processed ORD-1992722-01
2 Processed ORD-1992968-01
3 Processed ORD-1993016-01
4 Processed ORD-1993732-01
5 Processed ORD-1993783-01
6 Processed ORD-1994198-01
7 Processed ORD-1994251-01
8 Processed ORD-1994255-01
9 Processed ORD-1994335-01
10 Processed ORD-1994600-01
11 Processed ORD-1994629-01
12 Processed ORD-1994630-01
13 Processed ORD-1994651-01
14 Processed ORD-1994723-01
15 Processed ORD-1995002-01
16 Processed ORD-1995012-01
17 Processed ORD-1995110-01
18 Processed ORD-1995114-01
19 Processed ORD-1996633-01
20 Processed ORD-1996744-01
21 Processed ORD-1996747-01
22 Processed ORD-1997438-01
23 Processed ORD-1997463-01
24 Processed ORD-1998350-01
25 Processed ORD-1998420-01
26 Processed ORD-1998424-01
27 Processed ORD-1998426-01
28 Processed ORD-1998431-01
29 Processed ORD-1998452-01
30 Processed ORD-1999058-01
31 Processed ORD-1999155-01
32 Processed ORD-1999159-01
33 Processed ORD-1999175-01
34 Processed ORD-1999177-01
35 Processed ORD-1999178-01
36 Processed ORD-1999183-01
37 Processed ORD-1999187-01
38 Processed ORD-1999900-01
39 Processed ORD-1999903-01
40 Processed ORD-1999904-01
41 Processed ORD-1999967-01
42 Processed ORD-1999973-01
43 Processed ORD-2000752-01
44 Processed ORD-2000777-01
45 Processed ORD-2001648-01
46 Processed ORD-2003413-01
47 Processed ORD-2003433-01
48 Processed ORD-2003440-01
49 Processed ORD-2003444-01
50 Processed ORD-2004467-01
51 Processed ORD-2004469-01
52 Processed ORD-2004470-01
53 Processed ORD-2004498-01
54 Processed ORD-2004500-01
55 Processed ORD-2004505-01
56 Processed ORD-2005303-01
57 Processed ORD-2005326-01
58 Processed ORD-2005411-01
59 Processed ORD-2005417-01
60 Processed ORD-2005556-01
61 Processed ORD-2006128-01
62 Processed ORD-2006132-01
63 Processed ORD-2006241-01
64 Processed ORD-2006243-01
65 Processed ORD-2006244-01
66 Processed ORD-2006787-01
67 Processed ORD-2006793-01
68 Processed ORD-2006821-01
69 Processed ORD-2006872-01
70 Processed ORD-2007552-01
71 Processed ORD-2007587-01
72 Processed ORD-2007589-01
73 Processed ORD-2008343-01
74 Processed ORD-2008362-01
75 Processed ORD-2009154-01
76 Processed ORD-2009174-01
77 Processed ORD-2009175-01
78 Processed ORD-2010088-01
79 Processed ORD-2010773-01
80 Processed ORD-2010775-01
81 Processed ORD-2010777-01
82 Processed ORD-2010784-01
83 Processed ORD-2010860-01
84 Processed ORD-2010862-01
85 Processed ORD-2010869-01
86 Processed ORD-2011500-01
87 Processed ORD-2012738-01
88 Processed ORD-2014566-01
89 Processed ORD-2015194-01
90 Processed ORD-2016906-01
91 Processed ORD-2018899-01
92 Processed ORD-2018905-01
93 Processed ORD-2018985-01
94 Processed ORD-2020720-01
95 Processed ORD-2020721-01
96 Processed ORD-2020723-01
97 Processed ORD-2021396-01
98 Processed ORD-2021399-01
99 Processed ORD-2021780-01
100 Processed ORD-2021785-01
101 Processed ORD-2024069-01
102 Processed ORD-2032746-01
103 Processed ORD-2069193-01
104 Processed ORD-2070145-01
105 Processed ORD-2070973-01
106 Processed ORD-2071034-01
107 Processed ORD-2072075-01
108 Processed ORD-2072088-01
109 Processed ORD-2072105-01
110 Processed ORD-2073774-01
111 Processed ORD-2074649-01
112 Processed ORD-2074651-01
113 Processed ORD-2076321-01
114 Processed ORD-2076324-01
115 Processed ORD-2076372-01
116 Processed ORD-2077106-01
117 Processed ORD-2077108-01
118 Processed ORD-2077134-01
119 Processed ORD-2077864-01
120 Processed ORD-2078680-01
121 Processed ORD-2078681-01
122 Processed ORD-2078682-01
123 Processed ORD-2078683-01
124 Processed ORD-2078685-01
125 Processed ORD-2079804-01
126 Processed ORD-2080479-01
127 Processed ORD-2080531-01
128 Processed ORD-2081255-01
129 Processed ORD-2081259-01
130 Processed ORD-2081260-01
131 Processed ORD-2081262-01
132 Processed ORD-2084195-01
133 Processed ORD-2085915-01
134 Processed ORD-2085917-01
135 Processed ORD-2085918-01
136 Processed ORD-2085958-01
137 Processed ORD-2086928-01
138 Processed ORD-2086940-01
139 Processed ORD-2088094-01
140 Processed ORD-2088198-01
141 Processed ORD-2090528-01
142 Processed ORD-2090602-01
143 Processed ORD-2091356-01
144 Processed ORD-2091459-01
145 Processed ORD-2091463-01
146 Processed ORD-2092232-01
147 Processed ORD-2092234-01
148 Processed ORD-2092236-01
149 Processed ORD-2092237-01
150 Processed ORD-2092238-01
151 Processed ORD-2092289-01
152 Processed ORD-2092290-01
153 Processed ORD-2093083-01
154 Processed ORD-2093178-01
155 Processed ORD-2094856-01
156 Processed ORD-2094859-01
157 Processed ORD-2094862-01
158 Processed ORD-2097714-01
159 Processed ORD-2099348-01
160 Processed ORD-2099349-01
161 Processed ORD-2099352-01
162 Processed ORD-2099356-01
163 Processed ORD-2099386-01
164 Processed ORD-2100219-01
165 Processed ORD-2101915-01
166 Processed ORD-2101916-01
167 Processed ORD-2101917-01
168 Processed ORD-2101918-01
169 Processed ORD-2101919-01
170 Processed ORD-2103076-01
171 Processed ORD-2104088-01
172 Processed ORD-2105002-01
173 Processed ORD-2105910-01
174 Processed ORD-2105913-01
175 Processed ORD-2106764-01
176 Processed ORD-2106767-01
177 Processed ORD-2106768-01
178 Processed ORD-2107979-01
179 Processed ORD-2110640-01
180 Processed ORD-2110728-01
181 Processed ORD-2110764-01
182 Processed ORD-2111676-01
183 Processed ORD-2111684-01
184 Processed ORD-2112741-01
185 Processed ORD-2114858-01
186 Processed ORD-2115027-01
187 Processed ORD-2115029-01
188 Processed ORD-2115036-01
189 Processed ORD-2115040-01
190 Processed ORD-2115067-01
191 Processed ORD-2116120-01
192 Processed ORD-2116128-01
193 Processed ORD-2116205-01
194 Processed ORD-2116235-01
195 Processed ORD-2116246-01
196 Processed ORD-2117808-01
197 Processed ORD-2117926-01
198 Processed ORD-2117976-01
199 Processed ORD-2118841-01
200 Processed ORD-2118842-01
201 Processed ORD-2119398-01
202 Processed ORD-2119401-01
203 Processed ORD-2120320-01
204 Processed ORD-2120329-01
205 Processed ORD-2121109-01
206 Processed ORD-2122962-01
207 Processed ORD-2123718-01
208 Processed ORD-2123726-01
209 Processed ORD-2123737-01
210 Processed ORD-2127947-01
211 Processed ORD-2128873-01
212 Processed ORD-2130093-01
213 Processed ORD-2130099-01
214 Processed ORD-2130939-01
215 Processed ORD-2131606-01
216 Processed ORD-2133291-01

In [83]:
# All artifacts
arti_all_filter = final_df.filter(~pl.col("msec_filter_all").is_null())
display(arti_all_filter)
# Number of Samples with >= 1 artifacts
arti_all_filter["sample"].n_unique()

shape: (190, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-199296 ┆ 1-snv    ┆ chr7  ┆ 92462584  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 8-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-199373 ┆ 1-snv    ┆ chr6  ┆ 106553602 ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 2-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-199378 ┆ 1-snv    ┆ chr2  ┆ 209116217 ┆ … ┆ null       ┆ Artifact   ┆ Artifact   ┆ null      │
│ 3-01       ┆          ┆       ┆           ┆   ┆            ┆ suspicious ┆ suspicious ┆           │
│ ORD-199433 ┆ 1-snv    ┆ chr9  ┆ 98278972  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 5-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-199460 ┆ 1-snv    ┆ chr8  ┆ 117862875 ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-213160 ┆ 1-snv    ┆ chr17 ┆ 29483000  ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆           │
│ ORD-213160 ┆ 16-del   ┆ chr2  ┆ 225422558 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 2-ins    ┆ chr8  ┆ 117864264 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 3-ins    ┆ chr16 ┆ 3778439   ┆ … ┆ null       ┆ null       ┆ Artifact   ┆ filter 3: │
│ 1-01       ┆          ┆       ┆           ┆   ┆            ┆            ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

110

In [84]:
# Filter 1234
arti_filter_1234 = final_df.filter(~pl.col("msec_filter_1234").is_null())
display(arti_filter_1234)
# Number of Samples with >= 1 artifacts
arti_filter_1234["sample"].n_unique()

shape: (51, 37)
┌────────────┬──────────┬───────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ sample     ┆ mut_type ┆ chr   ┆ pos       ┆ … ┆ msec_filte ┆ msec_filte ┆ msec_filte ┆ comment   │
│ ---        ┆ ---      ┆ ---   ┆ ---       ┆   ┆ r_123      ┆ r_1234     ┆ r_all      ┆ ---       │
│ str        ┆ str      ┆ str   ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str       │
│            ┆          ┆       ┆           ┆   ┆ str        ┆ str        ┆ str        ┆           │
╞════════════╪══════════╪═══════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ ORD-199378 ┆ 1-snv    ┆ chr2  ┆ 209116217 ┆ … ┆ null       ┆ Artifact   ┆ Artifact   ┆ null      │
│ 3-01       ┆          ┆       ┆           ┆   ┆            ┆ suspicious ┆ suspicious ┆           │
│ ORD-199465 ┆ 1-snv    ┆ chr2  ┆ 25462068  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-199835 ┆ 1-snv    ┆ chr3  ┆ 185191097 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-199835 ┆ 1-snv    ┆ chrX  ┆ 39914756  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-199842 ┆ 18-ins   ┆ chr5  ┆ 79950727  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 0-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ …          ┆ …        ┆ …     ┆ …         ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ ORD-211780 ┆ 1-snv    ┆ chr3  ┆ 178952085 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 8-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-211884 ┆ 1-snv    ┆ chr2  ┆ 25463568  ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 1: │
│ 2-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 16-del   ┆ chr2  ┆ 225422558 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ filter 3: │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆ p is      │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ small,    │
│            ┆          ┆       ┆           ┆   ┆            ┆            ┆            ┆ but sup…  │
│ ORD-213160 ┆ 2-ins    ┆ chr8  ┆ 117864264 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 6-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
│ ORD-213329 ┆ 1-snv    ┆ chr11 ┆ 118343321 ┆ … ┆ Artifact   ┆ Artifact   ┆ Artifact   ┆ null      │
│ 1-01       ┆          ┆       ┆           ┆   ┆ suspicious ┆ suspicious ┆ suspicious ┆           │
└────────────┴──────────┴───────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

41

In [85]:
summarize_res(final_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬───────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_varints │
│ ---                             ┆ ---        ┆ ---      ┆ ---           │
│ str                             ┆ f64        ┆ i64      ┆ i32           │
╞═════════════════════════════════╪════════════╪══════════╪═══════════════╡
│ %_filter_1_mutation_intra_hair… ┆ 1.068091   ┆ 32       ┆ 2996          │
│ %_filter_2_hairpin_structure    ┆ 0.0        ┆ 0        ┆ 2996          │
│ %_filter_3_microhomology_induc… ┆ 0.834446   ┆ 25       ┆ 2996          │
│ %_filter_4_highly_homologous_r… ┆ 0.200267   ┆ 6        ┆ 2996          │
│ %_filter_5_soft_clipped_reads   ┆ 0.901202   ┆ 27       ┆ 2996          │
│ …                               ┆ …          ┆ …        ┆ …             │
│ %_filter_7_mutation_at_homopol… ┆ 0.033378   ┆ 1        ┆ 2996          │
│ %_filter_8_low_quality          ┆ 2.269693   ┆ 68       ┆ 2996          │
│ %_msec_filter_123               ┆ 1.502003   ┆ 45       ┆ 2996          │
│ %_msec_filter_1234              ┆ 1.70227    ┆ 51       ┆ 2996          │
│ %_msec_filter_all               ┆ 6.341789   ┆ 190      ┆ 2996          │
└─────────────────────────────────┴────────────┴──────────┴───────────────┘

### XML

In [86]:
msec_paths = sorted(glob.glob("../xml-micr-svf/*/*.microsec.tsv"))
len(msec_paths)

210

In [87]:
all_res = []

for i, path in enumerate(msec_paths):
	sample = os.path.basename(path).replace(".microsec.tsv", "")
	df = pl.read_csv(path, separator="\t").rename(lambda x: x.lower())
    
	all_res.append(df)
	print(f"{i+1} Processed {sample}")
    
final_df = pl.concat(all_res, how="vertical_relaxed").pipe(reorder_cols)

1 Processed ORD-1992722-01
2 Processed ORD-1992968-01
3 Processed ORD-1993016-01
4 Processed ORD-1993732-01
5 Processed ORD-1993783-01
6 Processed ORD-1994198-01
7 Processed ORD-1994251-01
8 Processed ORD-1994255-01
9 Processed ORD-1994335-01
10 Processed ORD-1994600-01
11 Processed ORD-1994629-01
12 Processed ORD-1994630-01
13 Processed ORD-1994651-01
14 Processed ORD-1994723-01
15 Processed ORD-1995002-01
16 Processed ORD-1995012-01
17 Processed ORD-1995110-01
18 Processed ORD-1995114-01
19 Processed ORD-1996633-01
20 Processed ORD-1996744-01
21 Processed ORD-1996747-01
22 Processed ORD-1997438-01
23 Processed ORD-1997463-01
24 Processed ORD-1998350-01
25 Processed ORD-1998420-01
26 Processed ORD-1998424-01
27 Processed ORD-1998426-01
28 Processed ORD-1998431-01
29 Processed ORD-1998452-01
30 Processed ORD-1999058-01
31 Processed ORD-1999155-01
32 Processed ORD-1999159-01
33 Processed ORD-1999175-01
34 Processed ORD-1999177-01
35 Processed ORD-1999178-01
36 Processed ORD-1999183-01
37 Processed ORD-1999187-01
38 Processed ORD-1999900-01
39 Processed ORD-1999903-01
40 Processed ORD-1999904-01
41 Processed ORD-1999967-01
42 Processed ORD-1999973-01
43 Processed ORD-2000752-01
44 Processed ORD-2000777-01
45 Processed ORD-2001648-01
46 Processed ORD-2003413-01
47 Processed ORD-2003433-01
48 Processed ORD-2003440-01
49 Processed ORD-2003444-01
50 Processed ORD-2004467-01
51 Processed ORD-2004469-01
52 Processed ORD-2004470-01
53 Processed ORD-2004498-01
54 Processed ORD-2004500-01
55 Processed ORD-2004505-01
56 Processed ORD-2005303-01
57 Processed ORD-2005326-01
58 Processed ORD-2005411-01
59 Processed ORD-2005417-01
60 Processed ORD-2005556-01
61 Processed ORD-2006128-01
62 Processed ORD-2006132-01
63 Processed ORD-2006241-01
64 Processed ORD-2006243-01
65 Processed ORD-2006244-01
66 Processed ORD-2006787-01
67 Processed ORD-2006793-01
68 Processed ORD-2006821-01
69 Processed ORD-2006872-01
70 Processed ORD-2007552-01
71 Processed ORD-2007587-01
72 Processed ORD-2007589-01
73 Processed ORD-2008343-01
74 Processed ORD-2008362-01
75 Processed ORD-2009154-01
76 Processed ORD-2009174-01
77 Processed ORD-2009175-01
78 Processed ORD-2010088-01
79 Processed ORD-2010773-01
80 Processed ORD-2010775-01
81 Processed ORD-2010777-01
82 Processed ORD-2010784-01
83 Processed ORD-2010860-01
84 Processed ORD-2010862-01
85 Processed ORD-2010869-01
86 Processed ORD-2011500-01
87 Processed ORD-2012738-01
88 Processed ORD-2014566-01
89 Processed ORD-2015194-01
90 Processed ORD-2016906-01
91 Processed ORD-2018899-01
92 Processed ORD-2018905-01
93 Processed ORD-2018985-01
94 Processed ORD-2020720-01
95 Processed ORD-2020721-01
96 Processed ORD-2020723-01
97 Processed ORD-2021396-01
98 Processed ORD-2021399-01
99 Processed ORD-2021780-01
100 Processed ORD-2021785-01
101 Processed ORD-2024069-01
102 Processed ORD-2032746-01
103 Processed ORD-2069193-01
104 Processed ORD-2070145-01
105 Processed ORD-2070973-01
106 Processed ORD-2071034-01
107 Processed ORD-2072075-01
108 Processed ORD-2072088-01
109 Processed ORD-2072105-01
110 Processed ORD-2073774-01
111 Processed ORD-2074649-01
112 Processed ORD-2074651-01
113 Processed ORD-2076321-01
114 Processed ORD-2076324-01
115 Processed ORD-2076372-01
116 Processed ORD-2077106-01
117 Processed ORD-2077108-01
118 Processed ORD-2077134-01
119 Processed ORD-2077864-01
120 Processed ORD-2078680-01
121 Processed ORD-2078681-01
122 Processed ORD-2078682-01
123 Processed ORD-2078683-01
124 Processed ORD-2078685-01
125 Processed ORD-2079804-01
126 Processed ORD-2080479-01
127 Processed ORD-2080531-01
128 Processed ORD-2081255-01
129 Processed ORD-2081259-01
130 Processed ORD-2081260-01
131 Processed ORD-2081262-01
132 Processed ORD-2084195-01
133 Processed ORD-2085915-01
134 Processed ORD-2085917-01
135 Processed ORD-2085918-01
136 Processed ORD-2085958-01
137 Processed ORD-2086928-01
138 Processed ORD-2086940-01
139 Processed ORD-2088094-01
140 Processed ORD-2088198-01
141 Processed ORD-2090528-01
142 Processed ORD-2090602-01
143 Processed ORD-2091356-01
144 Processed ORD-2091459-01
145 Processed ORD-2091463-01
146 Processed ORD-2092232-01
147 Processed ORD-2092234-01
148 Processed ORD-2092237-01
149 Processed ORD-2092238-01
150 Processed ORD-2092289-01
151 Processed ORD-2092290-01
152 Processed ORD-2093178-01
153 Processed ORD-2094856-01
154 Processed ORD-2094859-01
155 Processed ORD-2094862-01
156 Processed ORD-2097714-01
157 Processed ORD-2099348-01
158 Processed ORD-2099349-01
159 Processed ORD-2099352-01
160 Processed ORD-2099356-01
161 Processed ORD-2099386-01
162 Processed ORD-2100219-01
163 Processed ORD-2101915-01
164 Processed ORD-2101916-01
165 Processed ORD-2101917-01
166 Processed ORD-2101919-01
167 Processed ORD-2103076-01
168 Processed ORD-2104088-01
169 Processed ORD-2105002-01
170 Processed ORD-2105910-01
171 Processed ORD-2105913-01
172 Processed ORD-2106764-01
173 Processed ORD-2106767-01
174 Processed ORD-2106768-01
175 Processed ORD-2107979-01
176 Processed ORD-2110640-01
177 Processed ORD-2110764-01
178 Processed ORD-2111676-01
179 Processed ORD-2111684-01
180 Processed ORD-2112741-01
181 Processed ORD-2114858-01
182 Processed ORD-2115027-01
183 Processed ORD-2115029-01
184 Processed ORD-2115036-01
185 Processed ORD-2115040-01
186 Processed ORD-2115067-01
187 Processed ORD-2116128-01
188 Processed ORD-2116205-01
189 Processed ORD-2116235-01
190 Processed ORD-2117808-01
191 Processed ORD-2117926-01
192 Processed ORD-2117976-01
193 Processed ORD-2118841-01
194 Processed ORD-2118842-01
195 Processed ORD-2119398-01
196 Processed ORD-2119401-01
197 Processed ORD-2120320-01
198 Processed ORD-2120329-01
199 Processed ORD-2121109-01
200 Processed ORD-2122962-01
201 Processed ORD-2123718-01
202 Processed ORD-2123726-01
203 Processed ORD-2123737-01
204 Processed ORD-2127947-01
205 Processed ORD-2128873-01
206 Processed ORD-2130093-01
207 Processed ORD-2130099-01
208 Processed ORD-2130939-01
209 Processed ORD-2131606-01
210 Processed ORD-2133291-01

In [88]:
final_df

shape: (2_752, 47)
┌─────────────┬───────┬───────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ sample      ┆ chrom ┆ pos       ┆ ref ┆ … ┆ msec_filter ┆ msec_filter ┆ msec_filter ┆ comment    │
│ ---         ┆ ---   ┆ ---       ┆ --- ┆   ┆ _123        ┆ _1234       ┆ _all        ┆ ---        │
│ str         ┆ str   ┆ i64       ┆ str ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str        │
│             ┆       ┆           ┆     ┆   ┆ str         ┆ str         ┆ str         ┆            │
╞═════════════╪═══════╪═══════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ ORD-1992722 ┆ chr1  ┆ 120478170 ┆ G   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-1992722 ┆ chr1  ┆ 162724439 ┆ G   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-1992722 ┆ chr10 ┆ 104854199 ┆ T   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-1992722 ┆ chr11 ┆ 69625302  ┆ C   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-1992722 ┆ chr16 ┆ 341269    ┆ G   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ …           ┆ …     ┆ …         ┆ …   ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ ORD-2133291 ┆ chr17 ┆ 37856504  ┆ G   ┆ … ┆ null        ┆ null        ┆ null        ┆ filter 1:  │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆ p is       │
│             ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆ small, but │
│             ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆ sup…       │
│ ORD-2133291 ┆ chr22 ┆ 29108003  ┆ C   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-2133291 ┆ chr4  ┆ 1920021   ┆ A   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-2133291 ┆ chr7  ┆ 55268044  ┆ C   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
│ ORD-2133291 ┆ chrX  ┆ 66765516  ┆ C   ┆ … ┆ null        ┆ null        ┆ null        ┆ null       │
│ -01         ┆       ┆           ┆     ┆   ┆             ┆             ┆             ┆            │
└─────────────┴───────┴───────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [89]:
# All artifacts
arti_all_filter = final_df.filter(~pl.col("msec_filter_all").is_null())
display(arti_all_filter)
# Number of Samples with >= 1 artifacts
arti_all_filter["sample"].n_unique()

shape: (174, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-199296 ┆ chr7  ┆ 92462584  ┆ C          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 8-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-199373 ┆ chr6  ┆ 106553602 ┆ G          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 2-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-199378 ┆ chr2  ┆ 209116217 ┆ C          ┆ … ┆ null       ┆ Artifact  ┆ Artifact  ┆ null      │
│ 3-01       ┆       ┆           ┆            ┆   ┆            ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-199433 ┆ chr9  ┆ 98278972  ┆ T          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 5-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-199460 ┆ chr8  ┆ 117862875 ┆ T          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 0-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-213160 ┆ chr17 ┆ 29483000  ┆ G          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆           │
│ ORD-213160 ┆ chr2  ┆ 225422558 ┆ TTTCATCCAT ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 3: │
│ 6-01       ┆       ┆           ┆ GGTCATC    ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr8  ┆ 117864264 ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr11 ┆ 118343321 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr16 ┆ 3778439   ┆ T          ┆ … ┆ null       ┆ null      ┆ Artifact  ┆ filter 3: │
│ 1-01       ┆       ┆           ┆            ┆   ┆            ┆           ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

102

In [90]:
# Filter 1234
arti_filter_1234 = final_df.filter(~pl.col("msec_filter_1234").is_null())
display(arti_filter_1234)
# Number of Samples with >= 1 artifacts
arti_filter_1234["sample"].n_unique()

shape: (47, 47)
┌────────────┬───────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample     ┆ chrom ┆ pos       ┆ ref        ┆ … ┆ msec_filte ┆ msec_filt ┆ msec_filt ┆ comment   │
│ ---        ┆ ---   ┆ ---       ┆ ---        ┆   ┆ r_123      ┆ er_1234   ┆ er_all    ┆ ---       │
│ str        ┆ str   ┆ i64       ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆       ┆           ┆            ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═══════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ ORD-199378 ┆ chr2  ┆ 209116217 ┆ C          ┆ … ┆ null       ┆ Artifact  ┆ Artifact  ┆ null      │
│ 3-01       ┆       ┆           ┆            ┆   ┆            ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-199465 ┆ chr2  ┆ 25462068  ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-199835 ┆ chr3  ┆ 185191097 ┆ G          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 0-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-199835 ┆ chrX  ┆ 39914756  ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 0-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-199842 ┆ chrX  ┆ 44833932  ┆ AC         ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ …          ┆ …     ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ ORD-211780 ┆ chr3  ┆ 178952085 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 8-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-211884 ┆ chr2  ┆ 25463568  ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 1: │
│ 2-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr2  ┆ 225422558 ┆ TTTCATCCAT ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ filter 3: │
│ 6-01       ┆       ┆           ┆ GGTCATC    ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆ p is      │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆ small,    │
│            ┆       ┆           ┆            ┆   ┆            ┆           ┆           ┆ but sup…  │
│ ORD-213160 ┆ chr8  ┆ 117864264 ┆ C          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 6-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
│ ORD-213329 ┆ chr11 ┆ 118343321 ┆ A          ┆ … ┆ Artifact   ┆ Artifact  ┆ Artifact  ┆ null      │
│ 1-01       ┆       ┆           ┆            ┆   ┆ suspicious ┆ suspiciou ┆ suspiciou ┆           │
│            ┆       ┆           ┆            ┆   ┆            ┆ s         ┆ s         ┆           │
└────────────┴───────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

36

In [91]:
summarize_res(final_df)

shape: (11, 4)
┌─────────────────────────────────┬────────────┬──────────┬───────────────┐
│ filter                          ┆ percentage ┆ n_failed ┆ total_varints │
│ ---                             ┆ ---        ┆ ---      ┆ ---           │
│ str                             ┆ f64        ┆ i64      ┆ i32           │
╞═════════════════════════════════╪════════════╪══════════╪═══════════════╡
│ %_filter_1_mutation_intra_hair… ┆ 0.981105   ┆ 27       ┆ 2752          │
│ %_filter_2_hairpin_structure    ┆ 0.0        ┆ 0        ┆ 2752          │
│ %_filter_3_microhomology_induc… ┆ 0.763081   ┆ 21       ┆ 2752          │
│ %_filter_4_highly_homologous_r… ┆ 0.25436    ┆ 7        ┆ 2752          │
│ %_filter_5_soft_clipped_reads   ┆ 0.90843    ┆ 25       ┆ 2752          │
│ …                               ┆ …          ┆ …        ┆ …             │
│ %_filter_7_mutation_at_homopol… ┆ 0.036337   ┆ 1        ┆ 2752          │
│ %_filter_8_low_quality          ┆ 2.325581   ┆ 64       ┆ 2752          │
│ %_msec_filter_123               ┆ 1.453488   ┆ 40       ┆ 2752          │
│ %_msec_filter_1234              ┆ 1.707849   ┆ 47       ┆ 2752          │
│ %_msec_filter_all               ┆ 6.322674   ┆ 174      ┆ 2752          │
└─────────────────────────────────┴────────────┴──────────┴───────────────┘