In [1]:
#!/usr/bin/env python
import polars as pl
import os
import glob
from lxml import etree

## Functions

In [32]:
def get_test_type(xml_path: int) -> str:
	
	if not os.path.exists(xml_path):
		raise FileNotFoundError(f"No file found at {xml_path}")
	
	tree = etree.parse(xml_path)
	root = tree.getroot()
	return (
		root.
		xpath("//TestType")[0]
		.text.replace(" ", "")
		.replace("FoundationOneCDX", "FoundationOneCDx")
		.replace("FoundationOneLiquidCDx", "FoundationOneLiquidDx")
	)

In [33]:
def calc_arti_prop(artifact_pred_paths: list, arti_type: str, variant_source: str) -> pl.DataFrame:
	arti_prop = []

	# c = 1
	for path in artifact_pred_paths:
		
		artifact_pred = pl.read_csv(path, separator="\t", infer_schema_length=1000)

		if artifact_pred.is_empty():
			# print(f"{c}. Skipping {path} as it is empty. \n\tLikely Reasons include no corresponding BAMs, no variants in the VCF, or no variants after VUS exclusion")
			# c += 1
			continue

		variants = artifact_pred.shape[0]
		
		if arti_type.lower() == "micr":
			artifacts = artifact_pred.filter(~pl.col("msec_filter_1234").is_null()).shape[0]
		else:
			artifacts = artifact_pred.filter(~pl.col("pred")).shape[0]

		sample_name = os.path.basename(path).split(".")[0]
		xml_path = f"../data/{sample_name}.xml"
		test_type = get_test_type(xml_path)

		sample_stats = {
			"sample_name" : sample_name,
			"source": variant_source.upper(),
			"test_type": test_type,
			"arti_type": arti_type.upper(),
			"n_variants" : variants,
			"n_real" : (variants - artifacts),
			"n_artifacts" : artifacts,
			"proportion" : (artifacts / variants)
		}

		arti_prop.append(sample_stats)

	arti_prop = pl.DataFrame(arti_prop).sort("proportion", descending=True)
	return arti_prop

In [34]:
def get_stats(arti_prop: pl.DataFrame, damage_type: str = None, variant_source: str = None) -> None:
	
	prop_test_type = (
		arti_prop
		.group_by("test_type")
		.agg(
			pl.col("proportion").mean().alias("mean_proportion"),
			pl.col("proportion").count().alias("count"),
			pl.col("proportion").max().alias("max_proportion")
		)
	)

	prop_test_type_with_artifact = (
		arti_prop
		.filter(pl.col("proportion") > 0)
		.group_by("test_type")
		.agg(
			pl.col("proportion").mean().alias("mean_proportion"),
			pl.col("proportion").count().alias("count_>=1_artifact")
		)
	)
	
	mean_pct = arti_prop["proportion"].mean() * 100
	max_pct = arti_prop["proportion"].max() * 100
	n_samples = arti_prop.shape[0]
	has_artifact_df = arti_prop.filter(pl.col("proportion") > 0)
	n_with_artifacts = has_artifact_df.shape[0]
	mean_pct_arti_samples = has_artifact_df["proportion"].mean() * 100

	arti_type = damage_type.upper()
	print("Damage Type:", arti_type)
	print("Variant Source:", variant_source.upper())

	print(f"Samples analyzed: {n_samples}")
	print(f"Samples with ≥1 predicted {arti_type} artifact: {n_with_artifacts} ({n_with_artifacts / n_samples * 100:.1f}%)")
	print(f"Mean proportion of {arti_type} artifactual SNVs: {mean_pct:.2f}%")
	print(f"Max proportion of {arti_type} artifactual SNVs: {max_pct:.2f}%")
	print(f"Mean proportion of {arti_type} artifactual SNVs within samples with ≥1 predicted artifact: {mean_pct_arti_samples:.2f}%")
 
	print("\nResults stratified by test type:\n")
	for i in range(prop_test_type.shape[0]):

		test_type = prop_test_type[i, "test_type"]

		print(f"\t{test_type} samples analyzed: {prop_test_type[i, "count"]}")
		print(f"\t{test_type} max {arti_type} artifact proportion within samples: {prop_test_type[i, "max_proportion"] * 100:.2f}%")
		print(f"\t{test_type} mean {arti_type} artifact proportion within samples: {prop_test_type[i, "mean_proportion"] * 100:.2f}%")

		prop_test_type_with_artifact_filtered = prop_test_type_with_artifact.filter(pl.col("test_type") == test_type)

		if prop_test_type_with_artifact_filtered.shape[0]:
			print(f"\t{test_type} samples with {arti_type} artifact: {prop_test_type_with_artifact_filtered[0, "count_>=1_artifact"]}")
			print(f"\t{test_type} mean artifact proportion within samples with ≥1 detected {arti_type} artifacts: {prop_test_type_with_artifact_filtered[0, "mean_proportion"] * 100:.2f}%")

		print()
	print("-----------------\n")

In [35]:
def get_res(variant_source: str, damage_type: str, fp_cut: float, write_data: bool = True, exclude_vus = False) -> pl.DataFrame:
	
	if not exclude_vus:
		vus_token = ""
	else:
		vus_token = ".no_vus"
		print("VUS Excluded")

	if damage_type.lower() == "micr":
		search_pattern = f"../{variant_source.lower()}-{damage_type.lower()}-svf/*/*.microsec.tsv"
	else:
		search_pattern = f"../{variant_source.lower()}-{damage_type.lower()}-snvf/*/*.mobsnvf.{damage_type.lower()}{vus_token}.pred_fp-cut_{fp_cut:.0e}.tsv"
	
	arti_pred_paths = glob.glob(search_pattern)
	
	if not arti_pred_paths:
		raise FileNotFoundError (f"No predictions found at {search_pattern}")

	proportions = calc_arti_prop(arti_pred_paths, damage_type, variant_source)

	if fp_cut:
		print(f"FP-cut: {fp_cut}")

	get_stats(proportions, damage_type=damage_type, variant_source=variant_source)

	if write_data:
		if damage_type.lower() == "micr":
			proportions.write_csv(f"{damage_type.lower()}_proportions_per_sample.{variant_source.lower()}.tsv", separator="\t")
		else:
			proportions.write_csv(f"{damage_type.lower()}_proportions_per_sample.{variant_source.lower()}{vus_token}.fp-cut_{fp_cut:.0e}.tsv", separator="\t")
	
	return proportions

## MICR Artifacts

In [36]:
get_res("VCF", "MICR", None)

Damage Type: MICR
Variant Source: VCF
Samples analyzed: 1641
Samples with ≥1 predicted MICR artifact: 652 (39.7%)
Mean proportion of MICR artifactual SNVs: 2.27%
Max proportion of MICR artifactual SNVs: 38.00%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 5.72%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 874
	FoundationOneLiquidDx max MICR artifact proportion within samples: 25.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.38%
	FoundationOneLiquidDx samples with MICR artifact: 154
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 7.84%

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max MICR artifact proportion within samples: 38.00%
	FoundationOneCDx mean MICR artifact proportion within samples: 3.29%
	FoundationOneCDx samples with MICR artifact: 498
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 5.06%

-----------------

shape: (1_641, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1874772- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 50         ┆ 31     ┆ 19          ┆ 0.38       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1521390- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 49         ┆ 34     ┆ 15          ┆ 0.306122   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115040- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 10         ┆ 7      ┆ 3           ┆ 0.3        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 14         ┆ 10     ┆ 4           ┆ 0.285714   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1815786- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 108        ┆ 78     ┆ 30          ┆ 0.277778   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1458564- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 29         ┆ 29     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1964031- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 11         ┆ 11     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 15         ┆ 15     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 61         ┆ 61     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [37]:
get_res("XML", "MICR", None)

Damage Type: MICR
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted MICR artifact: 243 (15.1%)
Mean proportion of MICR artifactual SNVs: 1.39%
Max proportion of MICR artifactual SNVs: 33.33%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 9.20%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max MICR artifact proportion within samples: 33.33%
	FoundationOneCDx mean MICR artifact proportion within samples: 1.49%
	FoundationOneCDx samples with MICR artifact: 105
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 10.54%

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max MICR artifact proportion within samples: 25.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.30%
	FoundationOneLiquidDx samples with MICR artifact: 138
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 8.18%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1829552- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 4      ┆ 2           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 13         ┆ 9      ┆ 4           ┆ 0.307692   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115040- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 10         ┆ 7      ┆ 3           ┆ 0.3        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1880358- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 7          ┆ 5      ┆ 2           ┆ 0.285714   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1521390- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 15         ┆ 11     ┆ 4           ┆ 0.266667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1458564- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1964031- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 11         ┆ 11     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 15         ┆ 15     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 49         ┆ 49     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

## FP-CUT=1e-08

### FFPE Artifacts

In [38]:
get_res("VCF", "FFPE", 1e-08)

FP-cut: 1e-08
Damage Type: FFPE
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted FFPE artifact: 207 (12.6%)
Mean proportion of FFPE artifactual SNVs: 0.61%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 4.81%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 14.29%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.17%
	FoundationOneLiquidDx samples with FFPE artifact: 19
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 7.67%

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 1.11%
	FoundationOneCDx samples with FFPE artifact: 188
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 4.52%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2115029- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1587905- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 41         ┆ 32     ┆ 9           ┆ 0.219512   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1597650- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 43         ┆ 36     ┆ 7           ┆ 0.162791   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1964031- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1310482- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 43         ┆ 43     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 10         ┆ 10     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 39         ┆ 39     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [39]:
get_res("XML", "FFPE", 1e-08)

FP-cut: 1e-08
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted FFPE artifact: 34 (2.1%)
Mean proportion of FFPE artifactual SNVs: 0.20%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 9.50%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.24%
	FoundationOneCDx samples with FFPE artifact: 15
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 11.80%

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 14.29%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.17%
	FoundationOneLiquidDx samples with FFPE artifact: 19
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 7.67%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2115029- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1166521- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1431387- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1964031- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1310482- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 10         ┆ 10     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 39         ┆ 39     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [40]:
get_res("XML", "FFPE", 1e-08, exclude_vus=True)

VUS Excluded
FP-cut: 1e-08
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted FFPE artifact: 17 (1.1%)
Mean proportion of FFPE artifactual SNVs: 0.29%
Max proportion of FFPE artifactual SNVs: 50.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 25.62%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 33.33%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.15%
	FoundationOneLiquidDx samples with FFPE artifact: 5
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 23.52%

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max FFPE artifact proportion within samples: 50.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.46%
	FoundationOneCDx samples with FFPE artifact: 12
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 26.49%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 2      ┆ 2           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1431387- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 2          ┆ 1      ┆ 1           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1166521- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1537287- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1964031- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1310482- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 2          ┆ 2      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 3      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 11         ┆ 11     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

### OXOG Artifacts

In [41]:
get_res("VCF", "OXOG", 1e-08)

FP-cut: 1e-08
Damage Type: OXOG
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted OXOG artifact: 87 (5.3%)
Mean proportion of OXOG artifactual SNVs: 0.20%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 3.73%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.39%
	FoundationOneCDx samples with OXOG artifact: 84
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 3.57%

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneLiquidDx samples with OXOG artifact: 3
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 8.10%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1874772- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 42         ┆ 34     ┆ 8           ┆ 0.190476   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1050682- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1487773- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 41         ┆ 37     ┆ 4           ┆ 0.097561   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 11     ┆ 1           ┆ 0.083333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1458564- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 20         ┆ 20     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1964031- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 10         ┆ 10     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 39         ┆ 39     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [42]:
get_res("XML", "OXOG", 1e-08)

FP-cut: 1e-08
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted OXOG artifact: 8 (0.5%)
Mean proportion of OXOG artifactual SNVs: 0.06%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 12.83%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneLiquidDx samples with OXOG artifact: 3
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 8.10%

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.11%
	FoundationOneCDx samples with OXOG artifact: 5
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 15.67%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1850314- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 5          ┆ 4      ┆ 1           ┆ 0.2        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1050682- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1646731- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1499979- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1964031- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1310482- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 10         ┆ 10     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 12     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 39         ┆ 39     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [43]:
get_res("XML", "OXOG", 1e-08, exclude_vus=True)

VUS Excluded
FP-cut: 1e-08
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted OXOG artifact: 17 (1.1%)
Mean proportion of OXOG artifactual SNVs: 0.29%
Max proportion of OXOG artifactual SNVs: 50.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 25.62%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 33.33%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.15%
	FoundationOneLiquidDx samples with OXOG artifact: 5
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 23.52%

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max OXOG artifact proportion within samples: 50.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.46%
	FoundationOneCDx samples with OXOG artifact: 12
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 26.49%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 2      ┆ 2           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1431387- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 2          ┆ 1      ┆ 1           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1166521- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1537287- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-1964031- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1310482- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 2          ┆ 2      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2077108- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 3      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1741377- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2008343- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 11         ┆ 11     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

## FP-CUT = 5e-01

### FFPE artifacts

In [14]:
get_res("vcf", "ffpe", 5e-01)

FP-cut: 0.5
Damage Type: FFPE
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted artifact: 67 (4.1%)
Mean proportion of artifactual SNVs: 0.16%
Max proportion of artifactual SNVs: 25.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 4.04%

Results stratified by test type:

	FoundationOneLiquidDx samples: 630
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

	FoundationOneLiquidCDx samples: 245
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

	FoundationOneCDx samples: 138
	FoundationOneCDx max artifact proportion within samples: 9.09%
	FoundationOneCDx mean artifact proportion within samples: 0.10%
	FoundationOneCDx samples with >1 artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected artifacts: 7.18%

	FoundationOneCDX samples: 629
	FoundationOneCDX max artifact proportion within samples: 25.00%
	FoundationOneCDX mean artifact proportion within samples: 0.41%
	FoundationOneCDX samples with >1 artifact: 65
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 3.94%

-----------------

shape: (1_642, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 12    ┆ 9      ┆ 3           ┆ 0.25       │
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 12    ┆ 10     ┆ 2           ┆ 0.166667   │
│ ORD-2115029-01 ┆ FoundationOneCDX       ┆ 8     ┆ 7      ┆ 1           ┆ 0.125      │
│ ORD-1587905-01 ┆ FoundationOneCDX       ┆ 41    ┆ 36     ┆ 5           ┆ 0.121951   │
│ ORD-1914021-01 ┆ FoundationOneCDx       ┆ 11    ┆ 10     ┆ 1           ┆ 0.090909   │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 43    ┆ 43     ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 10    ┆ 10     ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 39    ┆ 39     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘

In [15]:
get_res("vcf", "oxog", 5e-01)

FP-cut: 0.5
Damage Type: OXOG
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted artifact: 24 (1.5%)
Mean proportion of artifactual SNVs: 0.07%
Max proportion of artifactual SNVs: 25.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 4.97%

Results stratified by test type:

	FoundationOneCDx samples: 138
	FoundationOneCDx max artifact proportion within samples: 0.00%
	FoundationOneCDx mean artifact proportion within samples: 0.00%

	FoundationOneLiquidDx samples: 630
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

	FoundationOneCDX samples: 629
	FoundationOneCDX max artifact proportion within samples: 25.00%
	FoundationOneCDX mean artifact proportion within samples: 0.19%
	FoundationOneCDX samples with >1 artifact: 24
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 4.97%

	FoundationOneLiquidCDx samples: 245
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

-----------------

shape: (1_642, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 12    ┆ 9      ┆ 3           ┆ 0.25       │
│ ORD-1874772-01 ┆ FoundationOneCDX       ┆ 42    ┆ 35     ┆ 7           ┆ 0.166667   │
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 12    ┆ 11     ┆ 1           ┆ 0.083333   │
│ ORD-1487773-01 ┆ FoundationOneCDX       ┆ 41    ┆ 38     ┆ 3           ┆ 0.073171   │
│ ORD-1127305-01 ┆ FoundationOneCDX       ┆ 31    ┆ 29     ┆ 2           ┆ 0.064516   │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 43    ┆ 43     ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 10    ┆ 10     ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 39    ┆ 39     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘

In [16]:
get_res("xml", "ffpe", 5e-01)

FP-cut: 0.5
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted artifact: 7 (0.4%)
Mean proportion of artifactual SNVs: 0.05%
Max proportion of artifactual SNVs: 25.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 11.38%

Results stratified by test type:

	FoundationOneCDx samples: 135
	FoundationOneCDx max artifact proportion within samples: 9.09%
	FoundationOneCDx mean artifact proportion within samples: 0.11%
	FoundationOneCDx samples with >1 artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected artifacts: 7.18%

	FoundationOneCDX samples: 605
	FoundationOneCDX max artifact proportion within samples: 25.00%
	FoundationOneCDX mean artifact proportion within samples: 0.11%
	FoundationOneCDX samples with >1 artifact: 5
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 13.06%

	FoundationOneLiquidCDx samples: 242
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

	FoundationOneLiquidDx samples: 624
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

-----------------

shape: (1_606, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 12    ┆ 9      ┆ 3           ┆ 0.25       │
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 12    ┆ 10     ┆ 2           ┆ 0.166667   │
│ ORD-2115029-01 ┆ FoundationOneCDX       ┆ 8     ┆ 7      ┆ 1           ┆ 0.125      │
│ ORD-1914021-01 ┆ FoundationOneCDx       ┆ 11    ┆ 10     ┆ 1           ┆ 0.090909   │
│ ORD-1595187-01 ┆ FoundationOneCDX       ┆ 17    ┆ 16     ┆ 1           ┆ 0.058824   │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 10    ┆ 10     ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 39    ┆ 39     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘

In [17]:
get_res("xml", "ffpe", 5e-01, exclude_vus=True)

VUS Excluded
FP-cut: 0.5
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted artifact: 5 (0.3%)
Mean proportion of artifactual SNVs: 0.09%
Max proportion of artifactual SNVs: 50.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 27.86%

Results stratified by test type:

	FoundationOneLiquidCDx samples: 227
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

	FoundationOneCDX samples: 558
	FoundationOneCDX max artifact proportion within samples: 50.00%
	FoundationOneCDX mean artifact proportion within samples: 0.22%
	FoundationOneCDX samples with >1 artifact: 4
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 30.65%

	FoundationOneLiquidDx samples: 578
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

	FoundationOneCDx samples: 126
	FoundationOneCDx max artifact proportion within samples: 16.67%
	FoundationOneCDx mean artifact proportion within samples: 0.13%
	FoundationOneCDx samples with >1 artifact: 1
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected artifacts: 16.67%

-----------------

shape: (1_489, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 4     ┆ 2      ┆ 2           ┆ 0.5        │
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 3     ┆ 2      ┆ 1           ┆ 0.333333   │
│ ORD-2115029-01 ┆ FoundationOneCDX       ┆ 4     ┆ 3      ┆ 1           ┆ 0.25       │
│ ORD-1914021-01 ┆ FoundationOneCDx       ┆ 6     ┆ 5      ┆ 1           ┆ 0.166667   │
│ ORD-1595187-01 ┆ FoundationOneCDX       ┆ 7     ┆ 6      ┆ 1           ┆ 0.142857   │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 4     ┆ 4      ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 2     ┆ 2      ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 3     ┆ 3      ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 4     ┆ 4      ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 11    ┆ 11     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘

### OXOG Artifacts

In [18]:
get_res("xml", "oxog", 5e-01)

FP-cut: 0.5
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted artifact: 2 (0.1%)
Mean proportion of artifactual SNVs: 0.02%
Max proportion of artifactual SNVs: 25.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 16.67%

Results stratified by test type:

	FoundationOneCDX samples: 605
	FoundationOneCDX max artifact proportion within samples: 25.00%
	FoundationOneCDX mean artifact proportion within samples: 0.06%
	FoundationOneCDX samples with >1 artifact: 2
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 16.67%

	FoundationOneLiquidDx samples: 624
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

	FoundationOneCDx samples: 135
	FoundationOneCDx max artifact proportion within samples: 0.00%
	FoundationOneCDx mean artifact proportion within samples: 0.00%

	FoundationOneLiquidCDx samples: 242
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

-----------------

shape: (1_606, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 12    ┆ 9      ┆ 3           ┆ 0.25       │
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 12    ┆ 11     ┆ 1           ┆ 0.083333   │
│ ORD-1702667-01 ┆ FoundationOneCDX       ┆ 7     ┆ 7      ┆ 0           ┆ 0.0        │
│ ORD-1287908-01 ┆ FoundationOneCDX       ┆ 6     ┆ 6      ┆ 0           ┆ 0.0        │
│ ORD-1774497-01 ┆ FoundationOneCDX       ┆ 8     ┆ 8      ┆ 0           ┆ 0.0        │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 10    ┆ 10     ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 12    ┆ 12     ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 39    ┆ 39     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘

In [19]:
get_res("xml", "oxog", 5e-01, exclude_vus=True)

VUS Excluded
FP-cut: 0.5
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted artifact: 5 (0.3%)
Mean proportion of artifactual SNVs: 0.09%
Max proportion of artifactual SNVs: 50.00%
Mean proportion of artifactual SNVs within samples with ≥1 predicted artifact: 27.86%

Results stratified by test type:

	FoundationOneLiquidCDx samples: 227
	FoundationOneLiquidCDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidCDx mean artifact proportion within samples: 0.00%

	FoundationOneCDx samples: 126
	FoundationOneCDx max artifact proportion within samples: 16.67%
	FoundationOneCDx mean artifact proportion within samples: 0.13%
	FoundationOneCDx samples with >1 artifact: 1
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected artifacts: 16.67%

	FoundationOneCDX samples: 558
	FoundationOneCDX max artifact proportion within samples: 50.00%
	FoundationOneCDX mean artifact proportion within samples: 0.22%
	FoundationOneCDX samples with >1 artifact: 4
	FoundationOneCDX mean artifact proportion within samples with ≥1 detected artifacts: 30.65%

	FoundationOneLiquidDx samples: 578
	FoundationOneLiquidDx max artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean artifact proportion within samples: 0.00%

-----------------

shape: (1_489, 6)
┌────────────────┬────────────────────────┬───────┬────────┬─────────────┬────────────┐
│ sample_name    ┆ test_type              ┆ n_snv ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---            ┆ ---                    ┆ ---   ┆ ---    ┆ ---         ┆ ---        │
│ str            ┆ str                    ┆ i64   ┆ i64    ┆ i64         ┆ f64        │
╞════════════════╪════════════════════════╪═══════╪════════╪═════════════╪════════════╡
│ ORD-2099356-01 ┆ FoundationOneCDX       ┆ 4     ┆ 2      ┆ 2           ┆ 0.5        │
│ ORD-1010565-01 ┆ FoundationOneCDX       ┆ 3     ┆ 2      ┆ 1           ┆ 0.333333   │
│ ORD-2115029-01 ┆ FoundationOneCDX       ┆ 4     ┆ 3      ┆ 1           ┆ 0.25       │
│ ORD-1914021-01 ┆ FoundationOneCDx       ┆ 6     ┆ 5      ┆ 1           ┆ 0.166667   │
│ ORD-1595187-01 ┆ FoundationOneCDX       ┆ 7     ┆ 6      ┆ 1           ┆ 0.142857   │
│ …              ┆ …                      ┆ …     ┆ …      ┆ …           ┆ …          │
│ ORD-1964031-01 ┆ FoundationOneCDx       ┆ 4     ┆ 4      ┆ 0           ┆ 0.0        │
│ ORD-1310482-01 ┆ FoundationOneCDX       ┆ 2     ┆ 2      ┆ 0           ┆ 0.0        │
│ ORD-2077108-01 ┆ FoundationOneCDX       ┆ 3     ┆ 3      ┆ 0           ┆ 0.0        │
│ ORD-1741377-01 ┆ FoundationOneLiquidDx  ┆ 4     ┆ 4      ┆ 0           ┆ 0.0        │
│ ORD-2008343-01 ┆ FoundationOneLiquidCDx ┆ 11    ┆ 11     ┆ 0           ┆ 0.0        │
└────────────────┴────────────────────────┴───────┴────────┴─────────────┴────────────┘