In [1]:
#!/usr/bin/env python
import polars as pl
import os
import glob
from lxml import etree

## Functions

In [2]:
def get_test_type(xml_path: int) -> str:
	
	if not os.path.exists(xml_path):
		raise FileNotFoundError(f"No file found at {xml_path}")
	
	tree = etree.parse(xml_path)
	root = tree.getroot()
	return (
		root
		.xpath("//TestType")[0]
		.text
		.replace(" ", "")
		.replace("FoundationOneCDX", "FoundationOneCDx")
		.replace("FoundationOneLiquidCDx", "FoundationOneLiquidDx")
	)

In [3]:
def snv_filter(df: pl.DataFrame):
    return df.filter(
        (pl.col("ref").str.len_chars() == 1) &
        (pl.col("alt").str.len_chars() == 1)
	)

In [4]:
def calc_arti_prop(artifact_pred_paths: list, arti_type: str, variant_source: str, vus: str, snv_only = True) -> pl.DataFrame:
	
	arti_prop = []
	for path in artifact_pred_paths:
		
		artifact_pred = pl.read_csv(path, separator="\t", infer_schema_length=1000).rename(lambda x: x.lower())
		
		if snv_only:
			artifact_pred = artifact_pred.pipe(snv_filter)

		## We calculate proportion of artifacts among VUS variants
		## Or proportion of artifacts among non-VUS variants
		if variant_source.lower() == "xml":
			# print(f"variants before vus filter {artifact_pred.height}")
			if vus == "exclude":
				artifact_pred = artifact_pred.filter(~pl.col("is_vus"))
				# print(f"variants after vus filter {artifact_pred.height}")
			elif vus == "vus_only":
				artifact_pred = artifact_pred.filter(pl.col("is_vus"))

		## Skip if the table is empty after filters
		if artifact_pred.is_empty():
			# print(f"{os.path.basename(path)} has no variant after VUS filtration")
			continue

		n_variants = artifact_pred.height
		
		if arti_type.lower() == "micr":
			## Artifacts identified by MicroSEC's Filter 1,2,3, or 4 are considered
			## as the rest are filter 5-8 are quality filters
			## Values in "msec_filter_1234" are either "artifact suspicious" 
			## i.e artifact or blank i.e not artifact
			n_artifacts = artifact_pred.filter(~pl.col("msec_filter_1234").is_null()).height
		else:
			n_artifacts = artifact_pred.filter(~pl.col("pred")).height

		sample_name = os.path.basename(path).split(".")[0]
		xml_path = f"../data/{sample_name}.xml"
		test_type = get_test_type(xml_path)

		sample_stats = {
			"sample_name" : sample_name,
			"source": variant_source.upper(),
			"test_type": test_type,
			"arti_type": arti_type.upper(),
			"n_variants" : n_variants,
			"n_real" : (n_variants - n_artifacts),
			"n_artifacts" : n_artifacts,
			"proportion" : (n_artifacts / n_variants)
		}

		arti_prop.append(sample_stats)

	arti_prop = pl.DataFrame(arti_prop).sort("proportion", descending=True)
	return arti_prop

In [5]:
def get_stats(arti_prop: pl.DataFrame, damage_type: str = None, variant_source: str = None) -> None:
	
	## Proportion summary of artifact among all samples stratified by test type
	prop_test_type = (
		arti_prop
		.group_by("test_type")
		.agg(
			pl.col("proportion").mean().alias("mean_proportion"),
			pl.col("proportion").count().alias("count"),
			pl.col("proportion").max().alias("max_proportion")
		)
	)

	## Proportion summary of artifacts among samples with artifact stratified by test type
	prop_test_type_with_artifact = (
		arti_prop
		.filter(pl.col("proportion") > 0)
		.group_by("test_type")
		.agg(
			pl.col("proportion").mean().alias("mean_proportion"),
			pl.col("proportion").count().alias("count_>=1_artifact")
		)
	)
	
	mean_pct = arti_prop["proportion"].mean() * 100
	max_pct = arti_prop["proportion"].max() * 100
	n_samples = arti_prop.height
	has_artifact_df = arti_prop.filter(pl.col("proportion") > 0)
	n_with_artifacts = has_artifact_df.height
	mean_pct_arti_samples = has_artifact_df["proportion"].mean() * 100

	arti_type = damage_type.upper()
	print("Damage Type:", arti_type)
	print("Variant Source:", variant_source.upper())

	print(f"Samples analyzed: {n_samples}")
	print(f"Samples with ≥1 predicted {arti_type} artifact: {n_with_artifacts} ({n_with_artifacts / n_samples * 100:.1f}%)")
	print(f"Mean proportion of {arti_type} artifactual SNVs: {mean_pct:.2f}%")
	print(f"Max proportion of {arti_type} artifactual SNVs: {max_pct:.2f}%")
	print(f"Mean proportion of {arti_type} artifactual SNVs within samples with ≥1 predicted artifact: {mean_pct_arti_samples:.2f}%")
 
	print("\nResults stratified by test type:\n")
	for i in range(prop_test_type.height):

		test_type = prop_test_type[i, "test_type"]

		print(f"\t{test_type} samples analyzed: {prop_test_type[i, "count"]}")
		print(f"\t{test_type} max {arti_type} artifact proportion within samples: {prop_test_type[i, "max_proportion"] * 100:.2f}%")
		print(f"\t{test_type} mean {arti_type} artifact proportion within samples: {prop_test_type[i, "mean_proportion"] * 100:.2f}%")

		prop_test_type_with_artifact_filtered = prop_test_type_with_artifact.filter(pl.col("test_type") == test_type)

		if prop_test_type_with_artifact_filtered.height:
			print(f"\t{test_type} samples with {arti_type} artifact: {prop_test_type_with_artifact_filtered[0, "count_>=1_artifact"]}")
			print(f"\t{test_type} mean artifact proportion within samples with ≥1 detected {arti_type} artifacts: {prop_test_type_with_artifact_filtered[0, "mean_proportion"] * 100:.2f}%")

		print()
	print("-----------------\n")

In [6]:
def get_res(variant_source: str, damage_type: str, fp_cut: float = None, write_data: bool = True, vus = "keep", snv_only: bool = True) -> pl.DataFrame:

	outdir = "artifact-proportions"
	os.makedirs(outdir, exist_ok=True)

	if damage_type.lower() != "micr":
		if not fp_cut:
			raise ValueError(f"fp_cut needs to be specified for {damage_type}")
	
	if variant_source.lower() != "xml":
		vus_token = ""
	else:
		if vus == "keep":
			vus_token = ""
			print("VUS are retained during proportion calculation")
		elif vus == "exclude":
			vus_token = ".no_vus"
			print("VUS are excluded from proportion calculation")
		elif vus == "vus_only":
			vus_token = ".vus_only"
			print("Proportions are calculated with only VUS")
		else:
			raise ValueError("allowed values for `vus` argument are 'keep', 'exclude', or 'vus_only'")
		

	if damage_type.lower() == "micr":
		search_pattern = f"../{variant_source.lower()}-{damage_type.lower()}-svf/*/*.microsec.tsv"
	else:
		search_pattern = f"../{variant_source.lower()}-{damage_type.lower()}-snvf/*/*.mobsnvf.{damage_type.lower()}.pred_fp-cut_{fp_cut:.0e}.tsv"
	
	arti_pred_paths = sorted(glob.glob(search_pattern))
	
	if not arti_pred_paths:
		raise FileNotFoundError (f"No predictions found at {search_pattern}")

	proportions = calc_arti_prop(arti_pred_paths, damage_type, variant_source, vus = vus, snv_only = snv_only)

	if fp_cut:
		print(f"FP-cut: {fp_cut}")

	get_stats(proportions, damage_type=damage_type, variant_source=variant_source)

	if write_data:
		if damage_type.lower() == "micr":
			proportions.write_csv(f"{outdir}/{damage_type.lower()}_proportions_per_sample.{variant_source.lower()}{vus_token}.tsv", separator="\t")
		else:
			proportions.write_csv(f"{outdir}/{damage_type.lower()}_proportions_per_sample.{variant_source.lower()}{vus_token}.fp-cut_{fp_cut:.0e}.tsv", separator="\t")
	
	return proportions

## MICR Artifacts

In [7]:
get_res("VCF", "MICR")

Damage Type: MICR
Variant Source: VCF
Samples analyzed: 1641
Samples with ≥1 predicted MICR artifact: 410 (25.0%)
Mean proportion of MICR artifactual SNVs: 1.50%
Max proportion of MICR artifactual SNVs: 38.10%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 5.99%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max MICR artifact proportion within samples: 38.10%
	FoundationOneCDx mean MICR artifact proportion within samples: 1.97%
	FoundationOneCDx samples with MICR artifact: 304
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 4.97%

	FoundationOneLiquidDx samples analyzed: 874
	FoundationOneLiquidDx max MICR artifact proportion within samples: 25.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.08%
	FoundationOneLiquidDx samples with MICR artifact: 106
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 8.92%

-----------------

shape: (1_641, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1874772- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 42         ┆ 26     ┆ 16          ┆ 0.380952   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 12         ┆ 8      ┆ 4           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1521390- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 40         ┆ 27     ┆ 13          ┆ 0.325      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1594210- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1641827- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 24         ┆ 24     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ VCF    ┆ FoundationO ┆ MICR      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [8]:
get_res("XML", "MICR")

VUS are retained during proportion calculation
Damage Type: MICR
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted MICR artifact: 136 (8.5%)
Mean proportion of MICR artifactual SNVs: 0.81%
Max proportion of MICR artifactual SNVs: 33.33%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 9.59%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max MICR artifact proportion within samples: 33.33%
	FoundationOneCDx mean MICR artifact proportion within samples: 0.49%
	FoundationOneCDx samples with MICR artifact: 31
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 11.73%

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max MICR artifact proportion within samples: 25.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.09%
	FoundationOneLiquidDx samples with MICR artifact: 105
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 8.96%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1829552- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 4      ┆ 2           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 12         ┆ 8      ┆ 4           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1594210- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1641827- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2085915- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 22         ┆ 22     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [9]:
get_res("XML", "MICR", vus="exclude")

VUS are excluded from proportion calculation
Damage Type: MICR
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted MICR artifact: 52 (3.5%)
Mean proportion of MICR artifactual SNVs: 1.11%
Max proportion of MICR artifactual SNVs: 100.00%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 31.70%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max MICR artifact proportion within samples: 100.00%
	FoundationOneCDx mean MICR artifact proportion within samples: 0.68%
	FoundationOneCDx samples with MICR artifact: 14
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 33.41%

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max MICR artifact proportion within samples: 100.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.47%
	FoundationOneLiquidDx samples with MICR artifact: 38
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 31.07%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1474930- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 1          ┆ 0      ┆ 1           ┆ 1.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1641912- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 1          ┆ 0      ┆ 1           ┆ 1.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1815030- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 1          ┆ 0      ┆ 1           ┆ 1.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1829552- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 2          ┆ 0      ┆ 2           ┆ 1.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 1      ┆ 3           ┆ 0.75       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 9          ┆ 9      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [10]:
get_res("XML", "MICR", vus="vus_only")

Proportions are calculated with only VUS
Damage Type: MICR
Variant Source: XML
Samples analyzed: 1603
Samples with ≥1 predicted MICR artifact: 91 (5.7%)
Mean proportion of MICR artifactual SNVs: 0.74%
Max proportion of MICR artifactual SNVs: 50.00%
Mean proportion of MICR artifactual SNVs within samples with ≥1 predicted artifact: 13.02%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 864
	FoundationOneLiquidDx max MICR artifact proportion within samples: 50.00%
	FoundationOneLiquidDx mean MICR artifact proportion within samples: 1.08%
	FoundationOneLiquidDx samples with MICR artifact: 72
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 12.96%

	FoundationOneCDx samples analyzed: 739
	FoundationOneCDx max MICR artifact proportion within samples: 28.57%
	FoundationOneCDx mean MICR artifact proportion within samples: 0.34%
	FoundationOneCDx samples with MICR artifact: 19
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected MICR artifacts: 13.24%

-----------------

shape: (1_603, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1641827- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 2          ┆ 1      ┆ 1           ┆ 0.5        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115040- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 7          ┆ 5      ┆ 2           ┆ 0.285714   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1524730- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1594210- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1857422- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 18         ┆ 18     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ MICR      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

## FP-CUT=1e-08

In the current implementation, variant sets after VUS stratification are not FDR predicted again.
Accuracy may be affected by this

### FFPE Artifacts

In [11]:
get_res("VCF", "FFPE", 1e-08)

FP-cut: 1e-08
Damage Type: FFPE
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted FFPE artifact: 207 (12.6%)
Mean proportion of FFPE artifactual SNVs: 0.61%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 4.81%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 14.29%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.17%
	FoundationOneLiquidDx samples with FFPE artifact: 19
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 7.67%

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 1.11%
	FoundationOneCDx samples with FFPE artifact: 188
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 4.52%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1587905- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 41         ┆ 32     ┆ 9           ┆ 0.219512   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1597650- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 43         ┆ 36     ┆ 7           ┆ 0.162791   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 24         ┆ 24     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [12]:
get_res("XML", "FFPE", 1e-08)

VUS are retained during proportion calculation
FP-cut: 1e-08
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted FFPE artifact: 34 (2.1%)
Mean proportion of FFPE artifactual SNVs: 0.20%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 9.50%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 14.29%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.17%
	FoundationOneLiquidDx samples with FFPE artifact: 19
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 7.67%

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.24%
	FoundationOneCDx samples with FFPE artifact: 15
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 11.80%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 6      ┆ 2           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1127305- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1166521- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 22         ┆ 22     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [13]:
get_res("XML", "FFPE", 1e-08, vus="exclude")

VUS are excluded from proportion calculation
FP-cut: 1e-08
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted FFPE artifact: 19 (1.3%)
Mean proportion of FFPE artifactual SNVs: 0.33%
Max proportion of FFPE artifactual SNVs: 50.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 25.55%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max FFPE artifact proportion within samples: 50.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.50%
	FoundationOneCDx samples with FFPE artifact: 13
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 26.37%

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 33.33%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.18%
	FoundationOneLiquidDx samples with FFPE artifact: 6
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 23.77%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1431387- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 2          ┆ 1      ┆ 1           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 2      ┆ 2           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1127305- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1166521- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 9          ┆ 9      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [14]:
get_res("XML", "FFPE", 1e-08, vus="vus_only")

Proportions are calculated with only VUS
FP-cut: 1e-08
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1603
Samples with ≥1 predicted FFPE artifact: 17 (1.1%)
Mean proportion of FFPE artifactual SNVs: 0.13%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 12.33%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 864
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.17%
	FoundationOneLiquidDx samples with FFPE artifact: 13
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 11.03%

	FoundationOneCDx samples analyzed: 739
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.09%
	FoundationOneCDx samples with FFPE artifact: 4
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 16.58%

-----------------

shape: (1_603, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1857422- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 9          ┆ 7      ┆ 2           ┆ 0.222222   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 5      ┆ 1           ┆ 0.166667   │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1806728- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 18         ┆ 18     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

### OXOG Artifacts

In [15]:
get_res("VCF", "OXOG", 1e-08)

FP-cut: 1e-08
Damage Type: OXOG
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted OXOG artifact: 87 (5.3%)
Mean proportion of OXOG artifactual SNVs: 0.20%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 3.73%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.39%
	FoundationOneCDx samples with OXOG artifact: 84
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 3.57%

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneLiquidDx samples with OXOG artifact: 3
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 8.10%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1874772- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 42         ┆ 34     ┆ 8           ┆ 0.190476   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1050682- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1487773- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 41         ┆ 37     ┆ 4           ┆ 0.097561   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 11     ┆ 1           ┆ 0.083333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 24         ┆ 24     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [16]:
get_res("XML", "OXOG", 1e-08)

VUS are retained during proportion calculation
FP-cut: 1e-08
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted OXOG artifact: 8 (0.5%)
Mean proportion of OXOG artifactual SNVs: 0.06%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 12.83%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.11%
	FoundationOneCDx samples with OXOG artifact: 5
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 15.67%

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneLiquidDx samples with OXOG artifact: 3
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 8.10%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1850314- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 5          ┆ 4      ┆ 1           ┆ 0.2        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1050682- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1499979- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1646731- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 22         ┆ 22     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [17]:
get_res("XML", "OXOG", 1e-08, vus="exclude")

VUS are excluded from proportion calculation
FP-cut: 1e-08
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted OXOG artifact: 7 (0.5%)
Mean proportion of OXOG artifactual SNVs: 0.21%
Max proportion of OXOG artifactual SNVs: 100.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 44.18%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max OXOG artifact proportion within samples: 100.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.35%
	FoundationOneCDx samples with OXOG artifact: 4
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 59.17%

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 33.33%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.09%
	FoundationOneLiquidDx samples with OXOG artifact: 3
	FoundationOneLiquidDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 24.21%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1499979- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 1          ┆ 0      ┆ 1           ┆ 1.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 1      ┆ 2           ┆ 0.666667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1850314- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 2          ┆ 1      ┆ 1           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1546506- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1050682- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 9          ┆ 9      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [18]:
get_res("XML", "OXOG", 1e-08, vus="vus_only")

Proportions are calculated with only VUS
FP-cut: 1e-08
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1603
Samples with ≥1 predicted OXOG artifact: 2 (0.1%)
Mean proportion of OXOG artifactual SNVs: 0.01%
Max proportion of OXOG artifactual SNVs: 12.50%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 11.81%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 864
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 739
	FoundationOneCDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneCDx samples with OXOG artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 11.81%

-----------------

shape: (1_603, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 9          ┆ 8      ┆ 1           ┆ 0.111111   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1001159- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 5          ┆ 5      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1020342- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1042000- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 18         ┆ 18     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

## FP-CUT = 5e-01

This is not a good cut off according to our testing.

### FFPE artifacts

In [19]:
get_res("vcf", "ffpe", 5e-01)

FP-cut: 0.5
Damage Type: FFPE
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted FFPE artifact: 67 (4.1%)
Mean proportion of FFPE artifactual SNVs: 0.16%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 4.04%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.35%
	FoundationOneCDx samples with FFPE artifact: 67
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 4.04%

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.00%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1587905- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 41         ┆ 36     ┆ 5           ┆ 0.121951   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1595187- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 66         ┆ 60     ┆ 6           ┆ 0.090909   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 24         ┆ 24     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ VCF    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [20]:
get_res("xml", "ffpe", 5e-01)

VUS are retained during proportion calculation
FP-cut: 0.5
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted FFPE artifact: 7 (0.4%)
Mean proportion of FFPE artifactual SNVs: 0.05%
Max proportion of FFPE artifactual SNVs: 25.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 11.38%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max FFPE artifact proportion within samples: 25.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.11%
	FoundationOneCDx samples with FFPE artifact: 7
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 11.38%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 12         ┆ 10     ┆ 2           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1914021- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 11         ┆ 10     ┆ 1           ┆ 0.090909   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1595187- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 17         ┆ 16     ┆ 1           ┆ 0.058824   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 22         ┆ 22     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [21]:
get_res("xml", "ffpe", 5e-01, vus="exclude")

VUS are excluded from proportion calculation
FP-cut: 0.5
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted FFPE artifact: 6 (0.4%)
Mean proportion of FFPE artifactual SNVs: 0.10%
Max proportion of FFPE artifactual SNVs: 50.00%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 25.60%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max FFPE artifact proportion within samples: 50.00%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.22%
	FoundationOneCDx samples with FFPE artifact: 6
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 25.60%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 2      ┆ 2           ┆ 0.5        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 3          ┆ 2      ┆ 1           ┆ 0.333333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2115029- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 3      ┆ 1           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1914021- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 5      ┆ 1           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1595187- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 7          ┆ 6      ┆ 1           ┆ 0.142857   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 9          ┆ 9      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [22]:
get_res("xml", "ffpe", 5e-01, vus="vus_only")

Proportions are calculated with only VUS
FP-cut: 0.5
Damage Type: FFPE
Variant Source: XML
Samples analyzed: 1603
Samples with ≥1 predicted FFPE artifact: 2 (0.1%)
Mean proportion of FFPE artifactual SNVs: 0.02%
Max proportion of FFPE artifactual SNVs: 22.22%
Mean proportion of FFPE artifactual SNVs within samples with ≥1 predicted artifact: 15.66%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 739
	FoundationOneCDx max FFPE artifact proportion within samples: 22.22%
	FoundationOneCDx mean FFPE artifact proportion within samples: 0.04%
	FoundationOneCDx samples with FFPE artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected FFPE artifacts: 15.66%

	FoundationOneLiquidDx samples analyzed: 864
	FoundationOneLiquidDx max FFPE artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean FFPE artifact proportion within samples: 0.00%

-----------------

shape: (1_603, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 9          ┆ 7      ┆ 2           ┆ 0.222222   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1598169- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 11         ┆ 10     ┆ 1           ┆ 0.090909   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1001159- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 5          ┆ 5      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1020342- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1042000- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 18         ┆ 18     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ FFPE      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

### OXOG Artifacts

In [23]:
get_res("vcf", "oxog", 5e-01)

FP-cut: 0.5
Damage Type: OXOG
Variant Source: VCF
Samples analyzed: 1642
Samples with ≥1 predicted OXOG artifact: 24 (1.5%)
Mean proportion of OXOG artifactual SNVs: 0.07%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 4.97%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 875
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 767
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.16%
	FoundationOneCDx samples with OXOG artifact: 24
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 4.97%

-----------------

shape: (1_642, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1874772- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 42         ┆ 35     ┆ 7           ┆ 0.166667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 11     ┆ 1           ┆ 0.083333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1487773- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 41         ┆ 38     ┆ 3           ┆ 0.073171   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1127305- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 31         ┆ 29     ┆ 2           ┆ 0.064516   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 24         ┆ 24     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ VCF    ┆ FoundationO ┆ OXOG      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [24]:
get_res("xml", "oxog", 5e-01)

VUS are retained during proportion calculation
FP-cut: 0.5
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1606
Samples with ≥1 predicted OXOG artifact: 2 (0.1%)
Mean proportion of OXOG artifactual SNVs: 0.02%
Max proportion of OXOG artifactual SNVs: 25.00%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 16.67%

Results stratified by test type:

	FoundationOneCDx samples analyzed: 740
	FoundationOneCDx max OXOG artifact proportion within samples: 25.00%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.05%
	FoundationOneCDx samples with OXOG artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 16.67%

	FoundationOneLiquidDx samples analyzed: 866
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.00%

-----------------

shape: (1_606, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 9      ┆ 3           ┆ 0.25       │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 12         ┆ 11     ┆ 1           ┆ 0.083333   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1001159- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1020342- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1042000- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 22         ┆ 22     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 13         ┆ 13     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 14         ┆ 14     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 7          ┆ 7      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [25]:
get_res("xml", "oxog", 5e-01, vus="exclude")

VUS are excluded from proportion calculation
FP-cut: 0.5
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1489
Samples with ≥1 predicted OXOG artifact: 1 (0.1%)
Mean proportion of OXOG artifactual SNVs: 0.04%
Max proportion of OXOG artifactual SNVs: 66.67%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 66.67%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 805
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 684
	FoundationOneCDx max OXOG artifact proportion within samples: 66.67%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.10%
	FoundationOneCDx samples with OXOG artifact: 1
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 66.67%

-----------------

shape: (1_489, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 3          ┆ 1      ┆ 2           ┆ 0.666667   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1001159- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 2          ┆ 2      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1020342- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 5          ┆ 5      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1048486- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1049250- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2128873- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 9          ┆ 9      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 1          ┆ 1      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘

In [26]:
get_res("xml", "oxog", 5e-01, vus="vus_only")

Proportions are calculated with only VUS
FP-cut: 0.5
Damage Type: OXOG
Variant Source: XML
Samples analyzed: 1603
Samples with ≥1 predicted OXOG artifact: 2 (0.1%)
Mean proportion of OXOG artifactual SNVs: 0.01%
Max proportion of OXOG artifactual SNVs: 12.50%
Mean proportion of OXOG artifactual SNVs within samples with ≥1 predicted artifact: 11.81%

Results stratified by test type:

	FoundationOneLiquidDx samples analyzed: 864
	FoundationOneLiquidDx max OXOG artifact proportion within samples: 0.00%
	FoundationOneLiquidDx mean OXOG artifact proportion within samples: 0.00%

	FoundationOneCDx samples analyzed: 739
	FoundationOneCDx max OXOG artifact proportion within samples: 12.50%
	FoundationOneCDx mean OXOG artifact proportion within samples: 0.03%
	FoundationOneCDx samples with OXOG artifact: 2
	FoundationOneCDx mean artifact proportion within samples with ≥1 detected OXOG artifacts: 11.81%

-----------------

shape: (1_603, 8)
┌──────────────┬────────┬─────────────┬───────────┬────────────┬────────┬─────────────┬────────────┐
│ sample_name  ┆ source ┆ test_type   ┆ arti_type ┆ n_variants ┆ n_real ┆ n_artifacts ┆ proportion │
│ ---          ┆ ---    ┆ ---         ┆ ---       ┆ ---        ┆ ---    ┆ ---         ┆ ---        │
│ str          ┆ str    ┆ str         ┆ str       ┆ i64        ┆ i64    ┆ i64         ┆ f64        │
╞══════════════╪════════╪═════════════╪═══════════╪════════════╪════════╪═════════════╪════════════╡
│ ORD-2099356- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 7      ┆ 1           ┆ 0.125      │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1010565- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 9          ┆ 8      ┆ 1           ┆ 0.111111   │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1001159- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 5          ┆ 5      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-1020342- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-1042000- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ …            ┆ …      ┆ …           ┆ …         ┆ …          ┆ …      ┆ …           ┆ …          │
│ ORD-2130093- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 18         ┆ 18     ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130099- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2130939- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 4          ┆ 4      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neCDx       ┆           ┆            ┆        ┆             ┆            │
│ ORD-2131606- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 8          ┆ 8      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
│ ORD-2133291- ┆ XML    ┆ FoundationO ┆ OXOG      ┆ 6          ┆ 6      ┆ 0           ┆ 0.0        │
│ 01           ┆        ┆ neLiquidDx  ┆           ┆            ┆        ┆             ┆            │
└──────────────┴────────┴─────────────┴───────────┴────────────┴────────┴─────────────┴────────────┘