In [1]:
import glob
import os
import polars as pl
import sys

sys.path.append(os.path.abspath("../common-ffpe-snvf/python"))

from mutation_signatures import read_variants

In [28]:
vcf_paths = glob.glob("../data/*.vcf")

all_vcf_snvs = []

for path in vcf_paths:
	vcf_snvs = read_variants(path, sample_name=os.path.basename(path).split(".")[0], snv_only=True, sort_variants=True)
	
	all_vcf_snvs.append(vcf_snvs)

all_vcf_snvs = pl.concat(all_vcf_snvs, how="vertical_relaxed").with_columns(pl.col("pos").cast(int))
all_vcf_snvs

shape: (17_745, 5)
┌───────┬───────────┬─────┬─────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ sample_id      │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---            │
│ str   ┆ i64       ┆ str ┆ str ┆ str            │
╞═══════╪═══════════╪═════╪═════╪════════════════╡
│ chr2  ┆ 29917796  ┆ C   ┆ T   ┆ ORD-1306616-01 │
│ chr2  ┆ 48026528  ┆ A   ┆ G   ┆ ORD-1306616-01 │
│ chr3  ┆ 183212035 ┆ A   ┆ T   ┆ ORD-1306616-01 │
│ chr5  ┆ 56184149  ┆ G   ┆ C   ┆ ORD-1306616-01 │
│ chr5  ┆ 149503827 ┆ G   ┆ A   ┆ ORD-1306616-01 │
│ …     ┆ …         ┆ …   ┆ …   ┆ …              │
│ chrX  ┆ 15841235  ┆ G   ┆ A   ┆ ORD-1677415-01 │
│ chr2  ┆ 25466800  ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr3  ┆ 169985730 ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr3  ┆ 191888349 ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr10 ┆ 8100732   ┆ C   ┆ G   ┆ ORD-1583898-01 │
└───────┴───────────┴─────┴─────┴────────────────┘

In [ ]:
xml_snv_paths = glob.glob("../xml-snvs/*/*.snv")

all_xml_snvs = []

for path in xml_snv_paths:
	xml_snvs = read_variants(path, sample_name=os.path.basename(path).split(".")[0], sort_variants=True)
	
	all_xml_snvs.append(xml_snvs)

all_xml_snvs = pl.concat(all_xml_snvs)
all_xml_snvs

shape: (7_014, 5)
┌───────┬───────────┬─────┬─────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ sample_id      │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---            │
│ str   ┆ i64       ┆ str ┆ str ┆ str            │
╞═══════╪═══════════╪═════╪═════╪════════════════╡
│ chr3  ┆ 12422929  ┆ G   ┆ A   ┆ ORD-1287908-01 │
│ chr3  ┆ 142172064 ┆ G   ┆ C   ┆ ORD-1287908-01 │
│ chr9  ┆ 98221925  ┆ C   ┆ T   ┆ ORD-1287908-01 │
│ chr12 ┆ 52379000  ┆ A   ┆ T   ┆ ORD-1287908-01 │
│ chr13 ┆ 32914817  ┆ G   ┆ A   ┆ ORD-1287908-01 │
│ …     ┆ …         ┆ …   ┆ …   ┆ …              │
│ chr16 ┆ 396226    ┆ A   ┆ C   ┆ ORD-1310482-01 │
│ chr17 ┆ 7578550   ┆ G   ┆ A   ┆ ORD-1310482-01 │
│ chr17 ┆ 41215376  ┆ T   ┆ C   ┆ ORD-1310482-01 │
│ chr17 ┆ 56772460  ┆ C   ┆ T   ┆ ORD-1310482-01 │
│ chr19 ┆ 10602496  ┆ G   ┆ A   ┆ ORD-1310482-01 │
└───────┴───────────┴─────┴─────┴────────────────┘

In [ ]:
xml_snv_not_in_vcf = all_xml_snvs.join(all_vcf_snvs, on=["chrom", "pos", "ref", "alt", "sample_id"], how = "anti")
xml_snv_not_in_vcf

shape: (0, 5)
┌───────┬─────┬─────┬─────┬───────────┐
│ chrom ┆ pos ┆ ref ┆ alt ┆ sample_id │
│ ---   ┆ --- ┆ --- ┆ --- ┆ ---       │
│ str   ┆ i64 ┆ str ┆ str ┆ str       │
╞═══════╪═════╪═════╪═════╪═══════════╡
└───────┴─────┴─────┴─────┴───────────┘

In [ ]:
xml_snv_in_vcf = all_xml_snvs.join(all_vcf_snvs, on=["chrom", "pos", "ref", "alt", "sample_id"], how = "semi")
xml_snv_in_vcf

shape: (7_014, 5)
┌───────┬───────────┬─────┬─────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ sample_id      │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---            │
│ str   ┆ i64       ┆ str ┆ str ┆ str            │
╞═══════╪═══════════╪═════╪═════╪════════════════╡
│ chr3  ┆ 12422929  ┆ G   ┆ A   ┆ ORD-1287908-01 │
│ chr3  ┆ 142172064 ┆ G   ┆ C   ┆ ORD-1287908-01 │
│ chr9  ┆ 98221925  ┆ C   ┆ T   ┆ ORD-1287908-01 │
│ chr12 ┆ 52379000  ┆ A   ┆ T   ┆ ORD-1287908-01 │
│ chr13 ┆ 32914817  ┆ G   ┆ A   ┆ ORD-1287908-01 │
│ …     ┆ …         ┆ …   ┆ …   ┆ …              │
│ chr16 ┆ 396226    ┆ A   ┆ C   ┆ ORD-1310482-01 │
│ chr17 ┆ 7578550   ┆ G   ┆ A   ┆ ORD-1310482-01 │
│ chr17 ┆ 41215376  ┆ T   ┆ C   ┆ ORD-1310482-01 │
│ chr17 ┆ 56772460  ┆ C   ┆ T   ┆ ORD-1310482-01 │
│ chr19 ┆ 10602496  ┆ G   ┆ A   ┆ ORD-1310482-01 │
└───────┴───────────┴─────┴─────┴────────────────┘

In [ ]:
vcf_snv_not_in_xml = all_vcf_snvs.join(all_xml_snvs, on=["chrom", "pos", "ref", "alt", "sample_id"], how = "anti")
vcf_snv_not_in_xml

shape: (10_731, 5)
┌───────┬───────────┬─────┬─────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ sample_id      │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---            │
│ str   ┆ i64       ┆ str ┆ str ┆ str            │
╞═══════╪═══════════╪═════╪═════╪════════════════╡
│ chr1  ┆ 27023878  ┆ C   ┆ T   ┆ ORD-1307819-01 │
│ chr1  ┆ 156851380 ┆ C   ┆ A   ┆ ORD-1307819-01 │
│ chr3  ┆ 12659993  ┆ C   ┆ A   ┆ ORD-1307819-01 │
│ chr3  ┆ 169999767 ┆ G   ┆ A   ┆ ORD-1307819-01 │
│ chr4  ┆ 143114379 ┆ C   ┆ T   ┆ ORD-1307819-01 │
│ …     ┆ …         ┆ …   ┆ …   ┆ …              │
│ chr19 ┆ 11097710  ┆ G   ┆ C   ┆ ORD-1677415-01 │
│ chr20 ┆ 30946706  ┆ G   ┆ C   ┆ ORD-1677415-01 │
│ chr20 ┆ 43963004  ┆ T   ┆ C   ┆ ORD-1677415-01 │
│ chr22 ┆ 21288262  ┆ G   ┆ A   ┆ ORD-1677415-01 │
│ chrX  ┆ 15841235  ┆ G   ┆ A   ┆ ORD-1677415-01 │
└───────┴───────────┴─────┴─────┴────────────────┘

In [ ]:
vcf_snv_in_xml = all_vcf_snvs.join(all_xml_snvs, on=["chrom", "pos", "ref", "alt", "sample_id"], how = "semi")
vcf_snv_in_xml

shape: (7_014, 5)
┌───────┬───────────┬─────┬─────┬────────────────┐
│ chrom ┆ pos       ┆ ref ┆ alt ┆ sample_id      │
│ ---   ┆ ---       ┆ --- ┆ --- ┆ ---            │
│ str   ┆ i64       ┆ str ┆ str ┆ str            │
╞═══════╪═══════════╪═════╪═════╪════════════════╡
│ chr2  ┆ 29917796  ┆ C   ┆ T   ┆ ORD-1306616-01 │
│ chr2  ┆ 48026528  ┆ A   ┆ G   ┆ ORD-1306616-01 │
│ chr3  ┆ 183212035 ┆ A   ┆ T   ┆ ORD-1306616-01 │
│ chr5  ┆ 56184149  ┆ G   ┆ C   ┆ ORD-1306616-01 │
│ chr5  ┆ 149503827 ┆ G   ┆ A   ┆ ORD-1306616-01 │
│ …     ┆ …         ┆ …   ┆ …   ┆ …              │
│ chr17 ┆ 38512390  ┆ G   ┆ A   ┆ ORD-1633622-01 │
│ chr2  ┆ 25466800  ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr3  ┆ 169985730 ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr3  ┆ 191888349 ┆ G   ┆ A   ┆ ORD-1583898-01 │
│ chr10 ┆ 8100732   ┆ C   ┆ G   ┆ ORD-1583898-01 │
└───────┴───────────┴─────┴─────┴────────────────┘

In [30]:
17_745 - 10_731

7014